### ISSUE TITLE
Support "complex ranges" in SemTK

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#146]
Right now SemTK will allow the restrictions in the model which limit the range to a subclass.   You can build nodegroups that use these ranges.   It just does not enforce the limited range when you query or ingest.    Enforcing the restriction on ingestion would be a good feature.   Work on this after finishing #59.

**Comment by cuddihyge** [comment]
Given 

- the difficulty of this task, 

- and our inability to identify a specific complex range use case that will be useful to RACK, 

I recommend we move this to "Tech debt" and not Pre-Release 5
