### ISSUE TITLE
Demonstrate RACK with Boeing code base

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#148]
After we get Boeing's code base, some initial RACK demonstration ideas include:
- ingest with our script
- share the .csv files with TA1s
- others?

**Comment by glguy** [comment]
I'm going to try and apply our Ada tools to this and see how far we get. There's an outstanding question about access to more build information, but we can start looking at the `.ada` files.

**Comment by kityansiu** [comment]
First set of data extracted and ingested into v5. Will open another another issue if there's more that can be extracted out of the Boeing code base.
