### ISSUE TITLE
Improve over Fuseki

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#149]
We know fuseki is small and free and SPARQL 1.1 compliant.  It  is not likely to meet our long term needs.
- how many triples are we targeting on what timeline
- what size does fuseki become un-workable
- are we planning a central data graph or including something better in RACK-in-a-box
- (cost / license)

**Comment by AbhaMoitra** [comment]
Closing this, further improvements will be in new / othr issues.
