### ISSUE TITLE
Query sample data against the "invariant" nodegroups

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#193]
I believe @cuddihyge mentioned that he and @glguy have developed two sets of nodegroups:

- One that checks for patterns that should be present in any valid data
- One that checks for patterns that should never occur in valid data

We should run these against the Turnstile data in CI.

@glguy can you point me to those nodegroups so I can get this started?

**Comment by AbhaMoitra** [comment]
User will select which MIL-STD-881 appendix to load - so there will no name clash.
