### ISSUE TITLE
Run sadl2owl in CI

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#194]
@kquick developed a tool called `sadl2owl` which can convert our SADL files into OWL without needing a full install of Eclipse. We should run this tool in CI to 

- guarantee that it continues to work for the subset of SADL that we use in our ontology
- and possibly provide some checks that the OWL we have checked into the repo is consistent with the current ontology

**Comment by tuxji** [comment]
We now have a dockerized SADL-Eclipse image (see <https://hub.docker.com/repository/docker/sadl/sadl-eclipse/>) which can translate a SADL project's SADL files to OWL files on the command line without needing a full install of Eclipse.  You are welcome to use this image in CI although you will have to decide exactly which SADL projects you will translate and whether their OWL files should be checked into source control or not.  Note that SADL or Jena (I don't know which) uses an unpredictable order when writing triples to OWL files, so the diff command would not be useful for comparing old versus new OWL files (the diff command would find differences every time).

**Comment by kityansiu** [comment]
All done! PR#[617](https://github.com/ge-high-assurance/RACK/pull/617).
