### ISSUE TITLE
ci: Run tests on the Github runner

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#204]
John and I discussed a few options for how to run tests in CI via email. We settled on trying to install RACK and run tests natively on the Github runner, rather than building the RACK-box Docker container and running the tests against that, as I tried in #201.

I've started work on this branch: https://github.com/ge-high-assurance/RACK/compare/lb/ci-test-native.

**Comment by tuxji** [comment]
@langston-barrett I noticed that the last two open pull requests are running 4 CI workflows (both pull request and push), which seems like overkill.  Ideally we'd run only 1 build and 1 lint workflow per pull request and/or push.  While you're adding the tests, can you prevent the redundant workflows from running?

**Comment by langston-barrett** [comment]
@tuxji Nice catch! I'll experiment with that on this branch since I'll be pushing a lot to it, but I'll try and split any relevant changes out into another PR, just in case it takes me a while to finish off that PR. I've made a new issue for this here: https://github.com/ge-high-assurance/RACK/issues/231
