### ISSUE TITLE
Install the ASSIST tools globally in RACK-box

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#212]
In RACK-Box v3.0, the ASSIST tools are available at `/home/ubuntu/RACK/RACK-Ontology/assist`. In our next release, we should install them globally in the image and put them on the `PATH` so that users don't have to hunt around to use them.

Also, #210 accidentally made it so that ASSIST is not packaged at all (it was formly included in a tarball of `RACK-Ontology/` that got copied into RACK-Box, but is no longer), so we should fix that as well.

**Comment by kquick** [comment]
I believe this is now resolved as of the v6 release.
