### ISSUE TITLE
CLI for Windows

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#220]
Create the equivalent CLI capability for Windows.

**Comment by tuxji** [comment]
Please elaborate.  How much of the CI workflow do you want to be run on both Linux and Windows?  What is the objective?

**Comment by kityansiu** [comment]
Apologies for the lack of clarity. What I meant is to have the same command line interface (https://github.com/ge-high-assurance/RACK/tree/master/cli) created for Linux also created for Windows.

**Comment by glguy** [comment]
As far as I knew the CLI works on Windows. I believe Paul uses it on Windows. Would the goal be to get more Windows-specific instructions into the README?

**Comment by cuddihyge** [comment]
I use CLI on windows inside a bash window, though.   So it behaves mostly like LINUX.

**Comment by kityansiu** [comment]
I added a few lines of GitBash commands to the CLI [README](https://github.com/ge-high-assurance/RACK/blob/master/cli/README.md).
