### ISSUE TITLE
Have the CI regenerate the prolog definitions for the ontology

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#221]
The files in the `assist/bin/ontology` are automatically generated from the current state of the OwlModels.

Since they get out of date quickly, it'd be nice for the CI to also regenerate these.

**Comment by langston-barrett** [comment]
> Since they get out of date quickly, it'd be nice for the CI to also regenerate these.

Are you considering having the CI system commit files to the repo? This seems potentially complex and risky. Or would we just generate them before we run the ASSIST tooling, like a compilation step?

**Comment by Ptival** [comment]
I was actually going to ask you @langston-barrett , because I do not know what capabilities we have, and what's best practice here! :-)

Would it be reasonable to have a hook that runs the tool and opens a pull request?
We could decide whether to have it on every commit, or at some fixed time interval if that gets too bothersome...

**Comment by langston-barrett** [comment]
Val and I discussed this today and concluded that we should first try integrating the generation of these files into the Packer build process, so that we don't have to have auto-generated files checked into the repo in the first place.

**Comment by Ptival** [comment]
No longer a priority as ontology changes fairly infrequenty. Closing, can be reopened if relevant.
