### ISSUE TITLE
python check_services failing for STR (TA3) and langston

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#226]

**Comment by cuddihyge** [comment]
I realized this is a python issue that may involve CLI more than anything on the docker end, so I added Eric and removed John for now.

**Comment by cuddihyge** [comment]
Notes from Tyler at steresearch

------------------------
update
------------------------
We’re referring to the programmatic endpoint exposed in the Python semtk3 library. It’s imported like this:

from semtk3 import check_services

There’s an illustrative example of how this is intended to be used – as a lambda function that tells docker when the service is ready – in the RACK codebase at:

RACK-Ontology/cli/tests/conftest.py

But the code that invokes it is actually commented out there, which seems to suggest this has been down for a while.

We actually learned of the GUI’s ability to check services after we sent this issue report out. It’s promising that there’s a working example of service checking!
-----------------------------------------
original
-----------------------------------------
SemTK exposes an endpoint that checks if associated services are ready. This feature would be very convenient for us to use to avoid errors when spinning up our containerized services. Unfortunately it is broken, unilaterally returning a value of False even once all associated services are up.

**Comment by glguy** [comment]
I'm not familiar with the services status API. Is this something I can have the CLI invoke before it does anything else?

**Comment by langston-barrett** [comment]
My experience when writing those tests was that `check_services` never reported that services were up, even when the GUI would, which is why that's commented out. It's probably worth checking whether that's still true, and actually investigating it if so.

**Comment by cuddihyge** [comment]
In my dev environment, when I runsemtk-python3's demo.py, check_services reports correctly.   I need more info on how you are running this.   This might be some kind of docker port issue?

Can I see your **semtk3.set_host("http://whatever")** code?

**Comment by cuddihyge** [comment]
@tuxji , is there something obvious that we're missing in order to get python to call each service's **serviceInfo/ping**

It is on the same port, obviously, but the path starts with serviceInfo instead of the normal service name.

**Comment by tuxji** [comment]
I don't see anything obviously missing from the Python code.  Sure, it doesn't verify that the "available" field both exists and has the value "yes" but the Java service code always returns "available": "yes" as far as I can see.  No one has reported what they actually saw logged via logger.ERROR(error) so I don't know what the problem might be.  My guess would be something incorrect was passed as the service's address or port.

```python
 103   │     def ping(self):
 104   │         '''
 105   │             logger.INFO(success)  or  logger.ERROR(error)
 106   │             returns True (success) or False (failure)
 107   │         '''
 108   │         try:
 109   │             res = self.post_to_simple("serviceInfo/ping")
 110   │             semtk3_logger.info(self.baseURL + self.get_simple_field_str(res, "available"))
 111   │             return True
 112   │         except Exception as e:
 113   │             semtk3_logger.error(str(e).replace("\n", ""))
 114   │             return False
```

**Comment by langston-barrett** [comment]
Steps to reproduce with the CLI test suite:

1. Apply this diff:
```diff
diff --git a/cli/tests/conftest.py b/cli/tests/conftest.py
index 7070f80..8768a16 100644
--- a/cli/tests/conftest.py
+++ b/cli/tests/conftest.py
@@ -13,8 +13,8 @@ def rack_in_a_box(docker_ip, docker_services) -> str:
     url = "http://{}".format(docker_ip)
     set_host(url)
     # TODO(lb): For some reason, check_services always returns false.
-    # docker_services.wait_until_responsive(
-    #     timeout=240.0, pause=0.1, check=lambda: check_services()
-    # )
-    sleep(120)
+    docker_services.wait_until_responsive(
+        timeout=240.0, pause=0.1, check=lambda: check_services()
+    )
+    # sleep(120)
     return url
```
2. Setup the CLI as you normally would for testing:
```bash
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
pip install -r dev/requirements.txt
python3 setup.py install
```
3. Run `pytest` and wait for the timeout

This totally might be an issue with the Docker configuation, see `cli/tests/docker-compose.yml` for how it's configured.

**Comment by cuddihyge** [comment]
@langston-barrett :  is this one solved?

**Comment by langston-barrett** [comment]
@cuddihyge I haven't tried it since I posted my last comment, so I'm not sure but I'd assume not.

**Comment by AbhaMoitra** [comment]
@langston-barrett : could you check if this is resolved. Thanks

**Comment by glguy** [comment]
> @langston-barrett : could you check if this is resolved. Thanks

I'll try running the reproduction instructions above to see if this still happens.

**Comment by glguy** [comment]
I tried restoring this check_services code and the tests once again stall. While the semtk3 instance was running in docker I tried manually opening python3 and calling `check_services` manually:

```python3
>>> import semtk3
>>> semtk3.set_host('http://127.0.0.1')
>>> semtk3.check_services()
http://127.0.0.1:12068/fdcCache/serviceInfo/ping: failed with reason: {"timestamp":"2021-02-17T17:39:25.389+0000","status":404,"error":"Not Found","message":"No message available","path":"/fdcCache/serviceInfo/ping"}Details:
```

Am I supposed to have a fdcCache service on the current development version of rack?

**Comment by glguy** [comment]
```
➜  ~ curl -d "" "http://127.0.0.1:12068/serviceInfo/ping"
{"message":"operations succeeded.","status":"success","simpleresults":{"available":"yes"}}%
```

It looks like the python3-semtk library is just polling the wrong address. I'll try fixing this in my semtk3-python branch.

**Comment by cuddihyge** [comment]
There is such a service, but we don't use it in RACK right now.  There may be a disconnect between semtk-python3 library and the list of services we start in RACK-in-a-box.    So the check-services() results are correct.
Do you think that any fix/change is worth doing?

**Comment by glguy** [comment]
@cuddihyge I fixed this in the branch of semtk-python3 that has the fixes/enhancements we need.

https://github.com/glguy/semtk-python3/commit/2ceee9a255fd0da92baf1b7946c4cc17c1fb4415

(This includes the two patches from [PR#9](https://github.com/ge-semtk/semtk-python3/pull/9) and then the new change for fdcCache)

**Comment by cuddihyge** [comment]
@glguy very nice catch.
But the problem is on the Java side, not the python side.    Leave the python as-is.
I'll push a fix into the next -dev container.

**Comment by glguy** [comment]
> @glguy very nice catch.
> But the problem is on the Java side, not the python side. Leave the python as-is.
> I'll push a fix into the next -dev container.

OK, cool, I'll drop that incorrect fix commit then.

**Comment by glguy** [comment]
This is fixed and working on our master branch using the latest rack and semtk-python3
