### ISSUE TITLE
Ontology lint failures not detected

### ISSUE THREAD

**Issue by kquick** [ge-high-assurance/RACK#229]
https://github.com/ge-high-assurance/RACK/pull/228/checks?check_run_id=1382862612

This fails the ontology linting step (see details) but the overall step is marked as success.

**Comment by langston-barrett** [comment]
See #223

**Comment by langston-barrett** [comment]
Fixed in https://github.com/ge-high-assurance/RACK/commit/2e919441b0e84c1b7e813d20ded6630d3fd9e3cb

**Comment by kquick** [comment]
Thanks!  Just wanted to make sure we didn't miss this.
