### ISSUE TITLE
Upload some Boeing data to Redshare with instruction for ingesting into RACK

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#268]
This is to verify our process before pushing it to Boeing's sharepoint for all TAs to use. The corresponding RACK box will continue to be provided for download as before. We will also ask GrammaTech to provide Boeing instance data along with scripts.

**Comment by kityansiu** [comment]
Ingestion of SRS, test scripts, and test results have been sent to Boeing for distribution to the ARCOS community. We have not yet tried to ingest our set with GrammaTech's set.
