### ISSUE TITLE
Add (sample) dateTime to Turnstile project

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#273]
This will provide syntax of dateTime for the TAs to use.

**Comment by kquick** [comment]
This is provided by https://github.com/ge-high-assurance/RACK/pull/253, so if this latter gets approved and merged that will resolve this issue.

**Comment by kquick** [comment]
Per clarification from our meeting today, we identified multiple locations for this:

* As part of the data present in the graph (PR #253 helps in this aspect)
* Syntax in CVS files for user-generated data ingestion
* Syntax in Nodegroup/queries

**Comment by AbhaMoitra** [comment]
This is currently blocked until additional dateTime format is included in SemTK. @cuddihyge  plans to push out an updated SemTk.

**Comment by cuddihyge** [comment]
@tuxji  and I have created a new -dev release that should handle the SADL date format.  Please let me know if it works correctly for you.

**Comment by AbhaMoitra** [comment]
I tested it out on dev branch pulled on 1/28/2021 and it works.
