### ISSUE TITLE
CLI: support multiple data graphs for relevant operations

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#274]
It came up that we want to be able to have multiple sets of data loaded at the same time, under different data graph names.

The CLI currently supports a `--data-graph` argument for certain commands, but we want to make sure that all relevant commands support such an argument, and that it indeed works the intended way.

**Comment by Ptival** [comment]
#278 makes progress on this.

**Comment by glguy** [comment]
Added in 525d1abf0b6d009655e1a8c0f01bee2a61029c53
