### ISSUE TITLE
subProperty bug if domain and range are both inherited

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#277]

**Comment by cuddihyge** [comment]
I appreciate that changing the SADL is a worthy work-around, but I'd prefer to keep this open and fix it if it can be done reasonably quickly.
Re-opening.

**Comment by glguy** [comment]
Ah, OK. I was just thinking of it as an ontology issue rather than the SemTK one.

**Comment by AbhaMoitra** [comment]
@russell-d-e : can you review this and close it if the issue you were seeing is now corrected.

**Comment by AbhaMoitra** [comment]
@russell-d-e : could you review this? Thanks

**Comment by russell-d-e** [comment]
I was not able to duplicate the issue with the latest dev docker.
