### ISSUE TITLE
unexpected results from union query

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#280]
The nodegroup "query Requirements without passed test" returned 2 extra rows that I did not expect. In the below picture, req HLR-1 is listed as not having a test (row 4), but that's not true looking at the results right below it (rows 5 & 6). Similarly, req IN-LLR-1 is listed as not having a test (row 9), but is not consistent with the results right below (rows 10 & 11).
![Capture](https://user-images.githubusercontent.com/12802455/105385969-eacced80-5be1-11eb-881c-41109bc52498.PNG)

**Comment by AbhaMoitra** [comment]
When I ran this as a "construct" query it gave an error. (This is the first time I ever ran a construct query.)

**Comment by cuddihyge** [comment]
I'll look at the query.   

@AbhaMoitra : As mentioned somewhere in the backlog, CONSTRUCT query functionality is incomplete and buggy.  I'd love to work on that.

**Comment by AbhaMoitra** [comment]
@cuddihyge : I remember that "construct" query functionality is not robust; but it may help you figure out what is the problem with the problem with the union query. Just my thought on it.

**Comment by cuddihyge** [comment]
I'm having trouble getting the nodegroups loaded because they don't match the model.
(I need to get my debugging environment to match what you may be doing in the docker container).

Am just running **setup-rack.sh**.   What am I missing?   @glguy ?

**Comment by cuddihyge** [comment]
Ring any bells?

?TEST_RESULT_0 Node property http://arcos.rack/TESTING#confirms range of 
     http://arcos.rack/PROV-S#ENTITY 
doesn't match model range of 
     http://arcos.rack/TESTING#TEST

**Comment by glguy** [comment]
That sounds like a relation range that was tightened in the ontology review and we'd need to edit the nodegroup.json to replace ENTITY there with TEST. I did go through and update the Turnstile nodegroups but I might have missed some in query

**Comment by glguy** [comment]
@cuddihyge I've updated the 3 queries that were affected by ontology changes

**Comment by cuddihyge** [comment]
@glguy  I pulled your updates and see that SystemInterfaceDefinition has two object properties called "source".   Both are sub-properties of wasDerivedFrom.    SYSTEM#source and SACM-S#source.   

If this is intended, I'll have to push some bug fixes to SemTK, as it not dis-ambiguating this property.
(I'll push these fixes either way).

If it is not intended, please remove the old one.

On a slight tangent, I caught these problems when running setup-rack.sh.   Do you think it would be helpful to set up a Jenkins server to run this with every check-in for integration testing (@kityansiu  @AbhaMoitra  what do you think?)  This setup might be tricky given the python environment but @vijayskumar or @tuxji  could help.

**Comment by glguy** [comment]
@cuddihyge I've been running `setup-rack.sh` too, but I didn't see any error output. Are we perhaps using different versions of SemTK that generate different results?

I don't think anything we're doing should use anything from SACM-S

**Comment by cuddihyge** [comment]
Very interesting problem:   The problem with this query is the use of 
         A . { minus {B} }  union { C } union {D}

Since the "minus" clause has no left hand side, it is interpretted as "nil minus {B}" and the nil always succeeds.  The creator of the query (me) had intended the minus {B} clause to fail if B didn't occur.

I'm open to ideas on how SemTK should generate the SPARQL in this situation.   We might also concede that the SPARQL does indeed match the nodegroup and the query should be reformulated.  I honestly don't know which is more correct.  

Summary: Currently SemTK queries which have a MINUS clause as a branch of a UNION will not work the way it appears like they're intended.

ps. I still think having jenkins run setup-rack.sh would be useful
pps.  I still don't think SystemInterfaceDefinition should have two properties named "source"

**Comment by glguy** [comment]
I believe we *do* run setup-rack.sh as part of the CI already.

**Comment by cuddihyge** [comment]
![image](https://user-images.githubusercontent.com/19863188/105552455-ee3fa200-5cd1-11eb-998e-b964772931e1.png)

I have found that a slight refactoring of this query makes it generate SPARQL that works.
(Just to clarify, the previous version generated the SPARQL I had expected, it is just that it was interpreted by the SPARQL engine in fuseki in a subtly tricky way.)

**IMPORTANT** This query won't work for you until I push a new semtk release and it gets picked up by rack.  Probably 1/25.  This query DID expose a SemTK sparql-generation bug.  I will not check it until there is a matching SemTK release.

I look forward to discussing.

**Comment by cuddihyge** [comment]
1. pushed the new nodegroup
2.  pushed fixes to Semtk.  Release v2.0.3-20210125
3. documented this little "gotcha" in the  [semtk wiki](https://github.com/ge-semtk/semtk/wiki/Queries-Advanced-Topics#combining-union-with-minus)

**Comment by AbhaMoitra** [comment]
@cuddihyge : when I ran this query in the version of RACK/SemTk of Monday or Tuesday of this week, I did not get any results.

**Comment by cuddihyge** [comment]
It wouldn't have worked Monday.  It should have worked Tuesday.
@tuxji and I have struggled a little with the deployment workflow, but it should be working.

Sorry, but could you confirm with a -dev container built today?

**Comment by cuddihyge** [comment]
It would also be helpful in debugging to confirm that when you load the query from the store into SPARQLgraph, you see the islands (shown in the picture above), not one connected nodegroup.   As there were two changes needed to make this work:
1) changing the query to islands 
2) deploying changes to SemTK so this island query generated properly

Again, sorry for the extra work, it works in my dev environment, but I guess we're debugging whether everything was deployed into RACK-in-a-box properly.

**Comment by AbhaMoitra** [comment]
@cuddihyge : I downloaded the dev build today (1/28) and all 3 queries ran fine. Now as well as earlier, the union query I was running was  the "3 island" one.

**Comment by AbhaMoitra** [comment]
@kityansiu : I think this can be closed.

**Comment by kityansiu** [comment]
Resolved. Thanks @cuddihyge!
