### ISSUE TITLE
ingestion creates duplicates when there are identical URI lookups

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#281]
[ingest_system.json.txt](https://github.com/ge-high-assurance/RACK/files/5852318/ingest_system.json.txt)

[SYSTEM.csv.txt](https://github.com/ge-high-assurance/RACK/files/5852321/SYSTEM.csv.txt)

Take the ".txt" off these files and use them to ingest.    

It seems that each column is being considered separately when generating unique URIs. The result is that you’ll find two instances of: Drivers, PX4 Autopilot, and External Communications int he resulting data.

NOTE: this does not fix the situation where two different columns are different subclasses of ENTITY with the same identifier.  If the class is different, then the URILookup is different and SemTK ingestion will not resolve.  It will create two different types of ENTITY with the same identifier.   This case requires a different ingestion strategy.

**Comment by glguy** [comment]
This works for me on rack/dev

**Comment by GregIthaca** [comment]
Now tested with the deployed v5.0 and it looks fixed.
