### ISSUE TITLE
CSV data file does not match Turnstile ontology

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#283]
In CounterApplication.sadl we have

![image](https://user-images.githubusercontent.com/28540315/106182819-63492680-616d-11eb-89e2-df0ad96021a1.png)

And in SoftwareComponent.csv we have

![image](https://user-images.githubusercontent.com/28540315/106182840-69d79e00-616d-11eb-9f0c-1fea9bac02f3.png)

Also, it seems "Mockup" is not defined in the ontology.

**Comment by kquick** [comment]
Do those CSV files have to be generated manually or is there an automated way to do it?  If they are manually generated that seems problematic and there will be a significant ongoing risk of them being out of date.

**Comment by glguy** [comment]
The Mockup entries have been removed.

**Comment by AbhaMoitra** [comment]
@kquick : The file SoftwareComponent.csv still has data values for headers controlFlowsToConditionallyId, controlFlowsToUnconditionallyId while that info is not present in the sadl file. While there are sadl queries to generate csv files (see 99-Utils/DataQueries.sadl) I do not see this csv file being generated via a query in that file. So, not sure where this csv file is coming from. Any suggestions on what should be done?

**Comment by kquick** [comment]
@AbhaMoitra , it looks like that csv file is generated by running the CLI tool against the Turnstile-Ontology/99-Utils/Data/Model.yaml file, so you should be able to run that and commit the changes therefrom.

**Comment by AbhaMoitra** [comment]
@glguy :  does this generation need to be part of some script so that it does not get out-of-synch in future. I have not "run the CLI" tool as mentioned above.
