### ISSUE TITLE
Updates needed for generic json

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#290]
We have discussed a couple of updates to be made to the generic json.

- Selectively use  "create if missing" (do not do it if that class has sub-classes)
- Can remove a number of "optional" settings on "identifier" : where ever the link to that class has an "optional" property
- Can remove "optional" for identifier of the "central class"

We will document in a wiki page that things should be loaded in the "correct" order, if there is circularity then we can help them; etc.

**Comment by AbhaMoitra** [comment]
Also, make both connections be identical (core ontology and Turnstile ontology) by unchecking :Enable OWL imports" in one of them.

**Comment by cuddihyge** [comment]
I've done this.  @glguy let me know if you don't understand or if I shouldn't have messed with your nodegroups.

EnableOwlImports is set to "true" when we load each SADL/owl file to its own graph, whose name matches the baseURI at the top of the SADL file.   In this case, SemTK reads the OwlImport triples in the model and chains the graph-loading and query FROM clauses to read model from all the graphs.

But this isn't what we're doing on RACK.  All models are loaded into one graph.

Checking the box makes these connections look different than the standard RACK connection and triggers extra dialogs in SPARQLgraph when @AbhaMoitra was switching between nodegroups.

**Comment by glguy** [comment]
> I've done this. @glguy let me know if you don't understand or if I shouldn't have messed with your nodegroups.

I have no objections

**Comment by AbhaMoitra** [comment]
@cuddihyge : I downloaded the dev version on 2/8/2021 and I am using nodegroups from the master branch. I dragged ingest_SystemComponent.json into SparqlGraph and I got the following error

![image](https://user-images.githubusercontent.com/28540315/107406134-1868d080-6ad6-11eb-8dd6-0d48daeb101b.png)

**Comment by cuddihyge** [comment]
I've regenerated them, hopefully against the latest owl.   Please retry.

**Comment by AbhaMoitra** [comment]
@cuddihyge : I retried and this json works. (I amstill  using dev from 2/8/2021).  However there are other jsons that still have errors. I am classifying these errors in to these categories:
* error in running a json: in running ingest_ACTIVITY.json I get the error "Job Status: Query failed: Error 400: Bad Request". This happens for a number of jsons - maybe they have the same root cause? 
*  error in loading a json: when I load ingest_ANALYSIS_REPORT.json I get the error "?ENTITY_2 Node property does not exist in the model: http://arcos.rack/FILE#fileParent". 
* error in loading a json: when I load ingest_COMPONENT.json the error is "Class does not exist in the model: http://arcos.rack/SOFTWARE#COMPONENT" 

I trimmed ingest_ACTIVITY.json (mentioned above) so that it still showed an error and this is what still gave an error. This may help you determine what is going on.
![image](https://user-images.githubusercontent.com/28540315/107520727-b9f82c80-6b7f-11eb-822b-30c3e723ec93.png)

**Comment by cuddihyge** [comment]
The second two error messages seem pretty clear.   The model has changed again.
Any ideas when these changes happened and why when I pull I'm not getting these changes?

**Comment by AbhaMoitra** [comment]
@cuddihyge : I'll look into what / when something changed for COMPONENT.

**Comment by cuddihyge** [comment]
Sorry, I believe that three files were not deleted from a previous run.

These are obsolete.  I've removed them.
![image](https://user-images.githubusercontent.com/19863188/107537237-a903e700-6b90-11eb-9f8e-61bb7465dca7.png)

@AbhaMoitra please ignore these three when testing.  They'll be gone from the next dev container.

**Comment by cuddihyge** [comment]
The 400 error is an ongoing (Docker?) problem that might be under a different issue, and I think will need @tuxji to help.

**Comment by cuddihyge** [comment]
So I suggest this one is ready to review.
The 400 error remains open under issue #289

**Comment by AbhaMoitra** [comment]
Have reviewed the changes as they appear in dev branch.
