### ISSUE TITLE
Improve CONSTRUCT queries on fuseki

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#301]
CONSTRUCT queries have many bugs on Fuseki.

Fix and JUNIT for the whole range of query types and expressions.

Noted problems include:
- BINDINGS (when a sparqlID has changed)
- UNIONS
- Use of (* +) on properties
- Generation with and without the ontology connected.

Horizontal benefit to STITCHES.

**Comment by AbhaMoitra** [comment]
Tested this out and it works very well. @russell-d-e has also tested this functionality out.
