### ISSUE TITLE
Generic nodegroups on GIT are out of synch with SADL and OWL files on GIT

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#306]
**First issue:** The generated nodegroups are out of synch with the GIT. For example, in the RACK-Ontology (in master branch), SOFTWARE.sadl is dated 2 months ago, SOFTWARE.owl is dated 26 days ago. And these files have a class called BINARY_BASIC_BLOCK. However, in the nodegroups in the master branch there is no ingestion or CDR for the corresponding class. This is just one example of where things seem to be missing.

**Second issue:** In nodegroups/CDR in the master branch on GIT, there is a file called ANALYSIS_REPORT.csv. At some earlier point ANALYSIS_REPORT was replaced by ANALYSIS_OUTPUT in the ontology. In nodegroups/CDR we have both ANALYSIS_REPORT.csv and ANALYSIS_OUTPUT.csv. Maybe what is happening is that the dir is not cleaned out and so the older file still hangs around. Maybe an update at the folder level may avoid this issue.

**Comment by cuddihyge** [comment]
I've removed the extra .csv files.
When I regenerate, everything else comes up the same (I use the .owl files).

What is the normal process for getting the .owl files in sync with the .SADL files?
Once that is done I'll try again.

**Comment by AbhaMoitra** [comment]
@cuddihyge : The first issue is not an issue - my mistake. And since the second issue is addressed; I'll close it and move it to Done column.
