### ISSUE TITLE
One Turnstile csv file does not have all the relevant info

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#307]
The following query

select distinct ?identifier_SystemComponent ?identifier_SystemRequirement ?text_SystemRequirement
where {
    ?SystemRequirement a <http://Turnstile/DevelopmentPlan#SystemRequirement> . 
    ?SystemRequirement <http://arcos.rack/PROV-S#identifier> ?identifier_SystemRequirement . 
    optional{ ?SystemRequirement <http://arcos.rack/PROV-S#description> ?text_SystemRequirement} . 
    optional{

    ?SystemRequirement <http://arcos.rack/REQUIREMENTS#governs> ?SystemComponent .
        ?SystemComponent a <http://Turnstile/DevelopmentPlan#SystemComponent> . 
        ?SystemComponent <http://arcos.rack/PROV-S#identifier> ?identifier_SystemComponent . 
    }

}".} to "99-Utils/Data/SystemRequirement.csv".

is not writing out optional fields like "governs"  as the query is not correct (governs does not have range SystemComponent, but has range SYSTEM).

**Comment by kityansiu** [comment]
Checked this out in dev. Everything looks good.
