### ISSUE TITLE
In Turnstile, incorrect partOf relationship present in csv data file

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#309]
The SADL query that generates SoftwareThread.csv needs to be corrected. Two statements that are outside of the "Optional" clause need to be moved inside the "Optional" clause so that the inner part of the query has the following structure

Ask SoftwareThreadCsv:"
select distinct ?identifier_SoftwareDesign ?identifier_SystemComponent ?identifier_SoftwareThread
where {
    ?SystemComponent a <http://Turnstile/DevelopmentPlan#SystemComponent> . 
    ?SystemComponent <http://arcos.rack/PROV-S#identifier> ?identifier_SystemComponent . 
    optional{
    ?SystemComponent <http://arcos.rack/SYSTEM#producedBy> ?SoftwareDesign .
        ?SoftwareDesign a <http://Turnstile/DevelopmentPlan#SoftwareDesign> . 
        ?SoftwareDesign <http://arcos.rack/PROV-S#identifier> ?identifier_SoftwareDesign . 
    }
    optional{
    ?SoftwareThread a <http://Turnstile/DevelopmentPlan#SoftwareThread> . 
    ?SoftwareThread <http://arcos.rack/PROV-S#identifier> ?identifier_SoftwareThread . 
    ?SoftwareThread <http://arcos.rack/SYSTEM#partOf> ?SystemComponent .
        ?SystemComponent a <http://Turnstile/DevelopmentPlan#SystemComponent> . 
        ?SystemComponent <http://arcos.rack/PROV-S#identifier> ?identifier_SystemComponent . 
    }

}"

Without this change, InputThread is a partOf Display etc. which is not correct.

**Comment by kityansiu** [comment]
Checked this out in dev. Everything looks good.
