### ISSUE TITLE
RACK wiki pages sometimes open with incorrect titles

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#333]
The <title> element for the "RACK Predefined Queries" wiki page is "RACK CLI" - this means that the title of a browser tab displaying this page is misleading.

There may be other examples of Wiki pages with incorrect titles - I've not checked exhaustively.

**Comment by clarissa-adelard** [comment]
Upon further investigation,  it would appear that GitHub is occasionally opening Wiki pages with an incorrect `<title>` element - however, this doesn't seem to happen consistently.

It may have something to do with whether I open the page directly or in a new tab, or it may be to do with the page from which I open the wiki page, but it has happened at least twice to two different Wiki pages.

If I can reproduce the problem, I will add a note to this issue.
