### ISSUE TITLE
query Control Flow from Function missing from predefined node groups

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#337]
According to the list of predefined RACK queries, there should be a query called `query Control Flow from Function` - however, there doesn't seem to be a corresponding nodegroup in `RACK/nodegroups/queries`.

**Comment by kityansiu** [comment]
We're working on a way to automatically update the predefined RACK queries wiki page. Stay tuned.

**Comment by kityansiu** [comment]
The [wiki page](https://github.com/ge-high-assurance/RACK/wiki/RACK-Predefined-Queries) is now auto generated.
