### ISSUE TITLE
RACK CLI Wiki page - use of virtual environments

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#342]
The instructions for installing dependencies recommend the use of a virtual environment, specifically `virtualenv`. 

Given that Python 3 now includes support for virtual environments (since Python 3.3), it would be better to use the standard Python 3 `venv` module, which avoids the need to install `virtualenv` (and `pipx`).

In other words, replace `virtualenv venv` with `python -m venv venv`.

**Comment by glguy** [comment]
I've incorporated this suggestion
