### ISSUE TITLE
RACK CLI Wiki page - clarify requirements for running on Windows

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#343]
The instructions for activating a Windows virtual environment are incorrect - in particular, according to the [Python 3 documentation](https://docs.python.org/3/library/venv.html), a Windows virtual environment is activated from the Windows command line as

`<venv>\Scripts\activate.bat`

without a source command.

**Comment by clarissa-adelard** [comment]
Ah - I'd missed the fact that the instructions are specific to GitBash. It's not clear how far you would get if you tried to run the setup script or the Rack CLI in a pure Windows environment - the shell scripts would obviously be a problem but it should be easy enough replace them with batch files.

In the meantime, I suggest the Wiki page clarifies this point and indicates where to find a copy of GitBash, which is part of the "Git for Windows" package:

https://gitforwindows.org

**Comment by kityansiu** [comment]
Thanks for the suggestion, @Robert-Adelard! I added a link to GitBash on the CLI wiki page.
