### ISSUE TITLE
Issue in ingesting Boeing data

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#345]
There is an error ingesting Boeing data in dev version of RACK.  The data is present on RedShare and dated 4/2/2021. The dev versions which gave this error are
* dev version pulled on 4/14/2021 and being run in Docker on a windows machine
* dev version being run in Docker on a mac

This issue may be related to SemTK.

@glguy @russell-d-e : please add additional details as needed.

**Comment by cuddihyge** [comment]
- Download   BoeingData_v5.1_20210402.zip from RedShare MockMessageCourier.
- run Load-BoeingData.sh

Reproduced the failure in a windows dev environment.

**Comment by cuddihyge** [comment]
I've gotten a handle on this. 

- I do not see a change in SemTK that would have caused this
- I do see how to change SemTK to prevent it from happening again

I'll push a new -dev docker some time today.
