### ISSUE TITLE
auto generate the wiki page "RACK Predefined Queries"

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#350]
Auto generate the wiki page [RACK Predefined Queries](https://github.com/ge-high-assurance/RACK/wiki/RACK-Predefined-Queries) based on [queries/store_data.csv](https://github.com/ge-high-assurance/RACK/blob/master/nodegroups/queries/store_data.csv). This will prevent us from having to manually keep this wiki page up to date. Feel free to modify the existing content on the page. For example, don't need to categorize the types of queries; don't need to keep the Future Queries section. Most important is the name of the query and the description. The other info in store_data.csv (like creator and json filename) are not needed on the wiki page.

_Bonus_: mechanism to update the wiki page whenever the file in the repo changes.

**Comment by baoluomeng** [comment]
Her is a solution. It requires developers to maintain all the queries in csv files preferably in a single csv file. And it could be stored anywhere in the repo, but the location must be fixed. The headers are the first row. As oppose to the current headers in the store_data.csv, we can make the headers more meaningful such as indicating the categories of the query on a column. The entire table will be displayed as it is on the Wiki page. I will modify CI script to automatically update the markdown file for the wiki page whenever a user update the query csv file. 

I will start an experimental RACK branch to display current queries/store_data.csv on the RACK Predefined Queries wiki page. Then you can determine whether you like it or not. @

**Comment by baoluomeng** [comment]
Below is what the Rack Predefined Queries page will look like. But we can modify the headers.
![image](https://user-images.githubusercontent.com/49253843/115893391-1ef4bc00-a426-11eb-83f1-ac1f366359bf.png)

**Comment by kityansiu** [comment]
BTW, [store_data.csv](https://github.com/ge-high-assurance/RACK/blob/master/nodegroups/queries/store_data.csv) is what's being used now to load the nodegroups to the nodegroup store in RACK. So when we build a RACK-in-a-Box, this is the file that developers update to get queries populated into RACK.

**Comment by baoluomeng** [comment]
Do you think if it is okay for developers to update the store_data.csv file, like changing the "ID" header to "Name" and appending a new column called "Category"? 

Or can we just display the store_data.csv as it is shown above?

**Comment by kityansiu** [comment]
> 
> 
> Do you think if it is okay for developers to update the store_data.csv file, like changing the "ID" header to "Name" and appending a new column called "Category"?
> 
> Or can we just display the store_data.csv as it is shown above?

@cuddihyge, what do you think? Can the headers in store_data.csv be changed?

**Comment by baoluomeng** [comment]
Below are tables of sample queries along with their descriptions. Structural Queries, Test Case Queries, and Test Result Queries are pre-loaded in RACK's Nodegroup store. Also below is a list of queries not pre-loaded in RACK but are supported by the current fidelity of the ontology. (RACK users can create these queries on their own.) The last section is a list of queries that are not supported by the fidelity of the current ontology but are ideas for inclusion in future releases.

## Queries Pre-loaded in RACK
ID                                          |  comments                                                                               |  creator    |  jsonFile
--------------------------------------------|-----------------------------------------------------------------------------------------|-------------|-------------------------------------------------
query Files of a Given Format               |  Find files of specified format                                                         |  langston   |  query Files of a Given Format.json
query nonuniqueIdentifiers                  |  Find identifiers that are not unique                                                   |  eric       |  query nonuniqueIdentifiers.json
query Requirements without Tests            |  Find requirements without a verifying test case                                        |  200001934  |  query Requirements without Tests.json
query Testcase without requirement          |  Find any test case that doesn't verify a requirement                                   |  200001934  |  query Testcase without requirement.json
query Requirements with failed test result  |  Find requirements with test failures                                                   |  200001934  |  query Requirements with failed test result.json
query Requirements decomposition            |  Recursively show all requirements satisfied by an original                             |  200001934  |  query Requirements decomposition.json
query Interface structure                   |  Find system source and destination for interface                                       |  200001934  |  query Interface structure.json
query Requirements with Tests               |  Find requirements verified by testcase                                                 |  200001934  |  query Requirements with Tests.json
query Trace Hazards to Tests                |  Trace hazard down to test case                                                         |  200001934  |  query Trace Hazards to Tests.json
query Trace Requirements to Tests           |  Recursively show all requirements which satisfy and verify a testcase                  |  200001934  |  query Trace Requirements to Tests.json
query Hazard structure                      |  Find system component associated with the hazards                                      |  200001934  |  query Hazard structure.json
query Terms consumedBy Requirement          |  Find data dictionary terms consumed by requirement(s)                                  |  200001934  |  query Terms consumedBy Requirement.json
query Compilation Inputs                    |  Find inputs used in compilation of executables                                         |  langston   |  query Compilation Inputs.json
query System Structure                      |  Extract system subcomponent structure contained under a given top-level anchor system  |  eric       |  query System Structure.json
query test empty thing                      |  Check for non-SYSTEM typed things with identifer and no other properties               |  200001934  |  query test empty thing.json
query Requirements without passed test      |  No Test, or no test result, or failure                                                 |  200001934  |  query Requirements without passed test.json
query Models for Thing                      |  Query that finds all the models and their types given a target THING identifier        |  em         |  query Models for Thing.json
query Get DataInsertedBy From Guid          |  Query that finds all all dataInsertedBy infromation for a THING selected by guid       |  dr         |  GetDataInsertedByFromGuid.json

### UnmitigatedHazards

Find all Hazards that do not have any mitigation.

HAZARD <-mitigates- ENTITY

### HazardMitigations

For each (or selected Hazard) find all Mitigating Entities

HAZARD <-mitigates- ENTITY

### HazardMitigationsFull

For each (or selected Hazard) find all Mitigating Entities, for each
mitigating entity find decomposed entities (recursive)

HAZARD <-mitigates- ENTITY[<-satisfies- ENTITY(0..*)]

### UpStreamRequirement

For each (or selected Requirement) find all consumed Data Dictionary
Terms, for each Data Dictionary Term then find all producing
Requirements.

REQUIREMENT <-consumedBy- DATA_DICTIONARY_TERM -providedBy-> REQUIREMENT

### ImplementedCode

For each (or selected Requirement) find all code files that implement
the requirement

REQUIREMENT <-satisfies- CODE_FILE

### CodeVerification

For each (or selected Code File) find all code files that implement
the requirement, then for each requirement find the verifying
TestCases, and for each TestCase get the TestResults.

CODE_FILE <-satisfies- REQUIREMENT <-verifies- TEST_CASE <-confirms- TEST_RESULT

### SystemHazards

For each system (or selected System) find all Hazards associated with
the System.

SYSTEM <-governs- REQUIREMENT [<-satisfies- ENTITY (0..*)] -mitigates-> HAZARD

## Query Ideas

These are some ideas for queries that may be useful to have available.
Some of these queries idea may not be able to be created with the
fidelity of the current ontology, but that may change as RACK matures.

### Ordering of Entity Generation

Queries that identify entities that were create/modified after source
Entity.  While these might not all be mistakes but they could be
information someone would want to audit and a large number of these
may provide indication of the quality of the development process.

* Requirements that have changed after being tested
* Requirements that changed after files that changed
* Files changed after test reports generated

### Independence

Queries that show the same person fulfilled multiple roles during the
development that should have been performed with independence

* Source files that where written by the same person as the test that verify the requirements

### User inspection

Queries that identify the changes by a person.

* Show changes made to the system by a particular user in a particular time window
* Show changes made by users working for a particular organization
* Show changes made outside of working hours

### Software

* Find libraries used in the system that are affected by known CVEs
* Find sources files written in C that don't have a Valgrind test report
* Verify that a subset of source files are built with a specific set of compiler flags
* Show all libraries used by the system

### Input Version

Queries that identify entities that were or were not developed to a
version of a source

* Show all requirements associated with a particular certification standard
* Show subset of source files affected by a particular standard
* Show all software that was developed to a prior version of a standard.

**Comment by cuddihyge** [comment]
store-data.csv is read by an automatic-ingestion routine that loads the nodegroups into the triplestore.
If you change the column names it will not work.

**Comment by cuddihyge** [comment]
you may add extra columns without hurting anything

**Comment by baoluomeng** [comment]
@kityansiu  you can know see the automatically generated ["Predefined query wiki"](https://github.com/ge-high-assurance/RACK/wiki/RACK-Predefined-Queries) page. I created a new workflow, which would automatically generate the md table from the [store_data.csv](https://github.com/ge-high-assurance/RACK/blob/master/nodegroups/queries/store_data.csv) file if there is any update to the file. So whatever is in the file will be displayed on ["the queries preloaded in RACK" section of the page](https://github.com/ge-high-assurance/RACK/wiki/RACK-Predefined-Queries#queries-pre-loaded-in-rack). The footer and header are from the _RACK-Predefined-Queries-header.md and _RACK-Predefined-Queries-footer.md pages in the RACK.wiki repo, which can be modified as needed. 

However, one caveat is that if you update the two pages: RACK-Predefined-Queries-header.md and _RACK-Predefined-Queries-footer.md, the RACK-Predefined-Queries page will not be updated. There are some technical details we need to figure out. But you can simply make a minor change to the store_data.csv to update the RACK-Predefined-Queries page with footer and header changes.

**Comment by kityansiu** [comment]
This looks awesome! Thank you!
