### ISSUE TITLE
query dataVal: add SWCOMPONENT check when ready

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#358]
Add the query nodegroup for: 
SWCOMPONENT w/o –wasInformedBy-> REQUIREMENT or -partOf -> SWCOMPONENT
when it's ready.

**Comment by AbhaMoitra** [comment]
This should instead read as 
   SWCOMPONENT w/o –wasImpactedBy-> REQUIREMENT or -subcomponentOf -> SWCOMPONENT

Note that we have

![image](https://user-images.githubusercontent.com/28540315/119192307-e7d9f080-ba4d-11eb-92d5-5d9e0de89cfd.png)
