### ISSUE TITLE
SPARQLGraph - construct query failed

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#365]
I tried to run a Construct query for the node group "query Requirement decomposition" but got an error as follows:

```
Query Generation Failed
Service "nodeGroup" failed
endpoint: generateConstruct 
full URL: http://192.168.254.212:12059/nodeGroup/generateConstruct 
xhr contents: 
  message: "operations failed."
  rationale: "nodeGroupService/generateConstruct threw java.lang.Exception Qualifier unsupported for CONSTRUCT queries: satisfies+\ncom.ge.research.semtk.belmont.NodeGroup.generateSparqlSubgraphClausesNodeItem(NodeGroup.java:2276)\ncom.ge.research.semtk.belmont.NodeGroup.generateSparqlSubgraphClausesNode(NodeGroup.java:2115)\ncom.ge.research.semtk.belmont.NodeGroup.generateSelectDistinctClause(NodeGroup.java:1868)\n..."
  status: "failure"
```

**Comment by glguy** [comment]
@cuddihyge Is this something SemTK could support, or perhaps something it could not support more gracefully?

**Comment by cuddihyge** [comment]
Yes.  @kityansiu and @AbhaMoitra have mentioned this to me via email.  I'm glad it getting into an issue we can rank and track.

There are different levels of quality fixes to this issue depending on how it ranks.   We could simply make a clearer error message.  It is also possible we could add some features to make the error less likely and easier to understand.

**Comment by cuddihyge** [comment]
I have improved the error handling when a CONSTRUCT query contains a qualifier.

But we would do well to have more conversations about this.   The reasonable ask is to CONSTRUCT the entire tree of requirements that decompose a top-level requirement.  (Just the way we get a list with SELECT DISTINCT).

There are plenty of subtleties in how CONSTRUCT queries and semTK work.  It is not clear that the same SPARQLgraph nodegroup would work well for both query types.

What SPARQLgraph needs to make this type of query work well is the ability to indicate that part of the nodegroup is not constructed, and only appears in the where clause.   

The closest we can come without this feature is something like this:
![image](https://user-images.githubusercontent.com/19863188/132064875-28a3be56-7cb1-4f1f-99a1-447e76896d19.png)

where ?REQUIREMENT has the constraint
```
?REQUIREMENT REQUIREMENTS:satisfies* ?R.  ?R PROV_S:identifier 'PIDS NAV Point'
```
which is annoying to type and more annoying or impossible to squeeze into a runtime constraint.

It does generate the proper result
![image](https://user-images.githubusercontent.com/19863188/132065093-3e1e3e77-f0ed-4299-9489-b4d02f24664d.png)

But in summary:   It is a very reasonable ask to come up with a clear way in the UI to specify that a certain part of the nodegroup is not CONSTRUCT-ed, but is only in the WHERE clause.  This way the contraint I typed above, could be drawn with another node that acts like a constraint (just like a in SELECT queries when you have a subgraph with nothing returned) and could be runtime constrained.

**Comment by cuddihyge** [comment]
Update:  an improvement to allow SPARQLgraph to easily build recursive subtree CONSTRUCT queries is in progress.

It looks like this:
![image](https://user-images.githubusercontent.com/19863188/133281196-1627c992-19ae-4a41-a0ce-7bec46f99e67.png)

Where ?REQUIREMENT_PARENT uses a new **construct checkbox** un-checked so it will not be constructed.  It will appear only in the WHERE clause.

![image](https://user-images.githubusercontent.com/19863188/133281614-66e1d17a-ccef-4677-b169-91ddd1a75e8e.png)

To make this clearer, SPARQLgraph display has been improved to show items differently depending on query mode.  When you change to **construct** the colored highlighting makes it more clear which items are constructed.

![image](https://user-images.githubusercontent.com/19863188/133282050-bef49b40-5536-4a79-bb19-b026d415c6f3.png)

I hope to release this for comment and testing soon.

```
A side-effect of this improvement will be changing the other checkbox from **"return"** to **"select"** as this much more accurately matches the SPARQL term, aligns with the **"construct"** checkbox next door, and makes the display changes which now occur with query type changes a little more intuitive.
```

**Comment by cuddihyge** [comment]
Here is a sample output.   (normally you'd include the identifiers too. )
![image](https://user-images.githubusercontent.com/19863188/133285099-3f1ca3d2-3fff-4bc7-a9bc-c3435c69789b.png)

**Comment by kityansiu** [comment]
working!
