### ISSUE TITLE
SPARQLGraph - Note: Path-finding timing out.  Search incomplete.

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#367]
If you try to drag a second instance of an entity onto the canvas, you get an error message

`Note: Path-finding timing out.  Search incomplete.`

For example, drag a REQUIREMENT followed by another REQUIREMENT, or a HAZARD followed by another HAZARD.

Given that you are then offered the choice to select the path manually, it is not clear that the message serves any purpose - it might be better just to allow the user to select the path manually without explaining that it was not possible to determine path automatically.

**Comment by glguy** [comment]
If you hold down <kbd>SHIFT</kbd> while dragging a node into the screen you can skip the path-finding search.

**Comment by cuddihyge** [comment]
For context:  before ARCOS, SemTK had not been used with an ontology where nearly every path passes through a common parent (e.g. ENTITY)    For the sake of other users, we don't want to remove this feature.

However, I feel the clunkiness here.  There are other great path-finding options available for exploration over the summer, and some UI clean-up that we can do for the next version.

Thanks for the feedback.

**Comment by cuddihyge** [comment]
This message does serve a purpose, as SPARQLgraph has still found the most likely paths through the model and lets the user choose from them.   We could lower the time-out, as the RACK ontology frequently spins for 10 seconds and I could see how that might get "old".  
We'll be looking at a longer term solution to path-finding in this ontology over the summer.

**Comment by AbhaMoitra** [comment]
Redundant with #245 so closing this.
