### ISSUE TITLE
Fuseki struggling with grammatech data

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#368]
unzip 2021_04_05_GrammaTech_Boeing_data_Rack_scripts.zip
cd 2021_04_05_GrammaTech_Boeing_data_Rack_scripts/Boeing-20210330
rack nodegroups import nodegroups_v5.0
rack data import import.yaml 

Fuseki can struggle and connection can be lost.

**Comment by cuddihyge** [comment]
I believe Eric's testing has confirmed that this problem is fixed @glguy can confirm and we can close this.

**Comment by glguy** [comment]
Fixing this required some changes to the GT generated nodegroups (changing Base URI and using no name bindings), and also updating my Fuseki version. I plan to meet with Paul soon to come up with a plan and to see if we can have SemTK generate SPARQL queries differently.
