### ISSUE TITLE
Update RACK CLI wiki page

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#371]
The RACK CLI wiki page has not kept up with changes to the names of node groups and other parameters.

Some examples:

- references to "ingestNN XXX" rather than "ingest_XXX" (throughout)
- references to data-model rather than data-graph (example of data ingestion configuration file format)

Please update the wiki page so that all the commands are correct and produce the output as advertised.

Thanks

**Comment by glguy** [comment]
The CLI was recently refreshed
