### ISSUE TITLE
Local copy of RACK documentation has some documents missing

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#375]
The local copy of the RACK documentation that is installed at

http://RACK-SERVER/documentation.html

does not contain copies of

https://github.com/ge-high-assurance/RACK/wiki/RACK-Preloaded-Documents
https://github.com/ge-high-assurance/RACK/wiki/RACK-v5.0-Ontology-Changelog

Also, for some unknown reason, the section titles are in a different order and contain hyphens rather than spaces.

**Comment by kityansiu** [comment]
We chose not to include these in the documentation.
