### ISSUE TITLE
Ordering of topics in RACK Wiki / documentation

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#379]
The ordering of topics in the RACK Wiki is somewhat arbitrary - the ordering of topics in the RACK documentation is equally arbitrary in a different way. Neither ordering seems to have any rationale - in the absence of a sensible ordering, alphabetical ordering would be an improvement.

**Comment by kityansiu** [comment]
I respectfully disagree. We may not agree on the ordering, but it's not arbitrary.
