### ISSUE TITLE
Missing REST Cookbook page?

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#384]
The REST API Swagger Demo page in the Wiki contains a couple of links to the SemTK REST Cookbook page:

https://github.com/ge-semtk/semtk/wiki/REST-cookbook

However, there is no such page in the SemTK Wiki - the closest is 

https://github.com/ge-semtk/semtk/wiki/REST-API

**Comment by kityansiu** [comment]
fixed
