### ISSUE TITLE
note for content needs to be updated

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#388]
We have a copy/paste error on the note for content in [PROV-S](https://github.com/ge-high-assurance/RACK/blob/master/RACK-Ontology/ontology/PROV-S.sadl).

![image](https://user-images.githubusercontent.com/12802455/118150227-5086f480-b3e0-11eb-98bf-6748332c7061.png)

Please also check the edit history comments (lines 16, 17). I think these were decisions we reverted.

**Comment by AbhaMoitra** [comment]
@kityansiu : I did this in a branch called correctProvS-Note. Can you approve / push this to master?
