### ISSUE TITLE
Incorrect property range in SemTK

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#411]
With the dev version that was pulled on 5/21/2021, I see the following in SemTK.

![fig1](https://user-images.githubusercontent.com/28540315/119673944-ca1fd900-be09-11eb-9362-9fe88a821d0c.png)

Note the range of wasInformedBy is THING. However in the core ontology we have the range as ACTIVITY.

![fig2](https://user-images.githubusercontent.com/28540315/119674074-e6237a80-be09-11eb-91e0-8c9dc6c901e1.png)

This is probably arising from the the SRI overlay ontology which has statement of the form

wasInformedBy of A1 only has values of type {A2 or A3}.

A2 and A3 are both of type ACTIVITY so it is not changing the core ontology property. 

So not sure the reason for range to be set to THING.

**Comment by cuddihyge** [comment]
The root cause of this problem seems to be an “error” in the ontology:

http://arcos.descert/DesCert#SystemRequirementsDefinition  wasInformedBy   http://arcos.descert/DesCert#SystemConOps

where SystemConOps is a type of ENTITY  instead of ACTIVITY.   Other ConOps seem to subclasses of ACTIVITY.

**Comment by AbhaMoitra** [comment]
@cuddihyge : This was corrected in the SRI ontology. Now it reads 

wasInformedBy of SystemRequirementsDefinition only has values of type DevelopSystemConOps.

So, maybe the dev version I was using was from before this ontology change was done?  

I'll close this issue at this point.

**Comment by cuddihyge** [comment]
Just FYI that I just did a "git pull" before debugging and I did not get DevelopSystemConOps.   
So git does not yet have this change (it is NOT simply an old -dev docker image)

**Comment by AbhaMoitra** [comment]
@cuddihyge : It turned out that the SRI.owl file was not updated and that explains, I think, what you saw above. We will push SRI.owl file now to master.
