### ISSUE TITLE
CLI cannot clear data separate from import?

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#413]
As we start to have multiple performers generating intertwining datasets, the fact that it's not possible to explicitly clear the data without loading something in becomes slightly challenging.  It would be helpful if
```bash
rack data import --clear
```
worked as a standalone command.

Assume I have a RACK-in-a-box instance which already has some data imported - for example the result of running cli/setup-rach.sh has Turnstile data in the http://rack001/data datagraph.

I want to load the data from one or more performer (for example, from GE and then from GrammaTech). However, the bash ingestion scripts (as written) do not clear the data first (and if they did, you wouldn't be able to merge data as proposed). If I run the scripts from GE followed by GrammaTech, then any pre-existing data in the RACK instance will be merged with the new inputs.

**Comment by kityansiu** [comment]
I agree that this would be a nice enhancement to the CLI. Similarly for the model graph, it would be nice to be able to clear independent of the import step. We would have to look into this post v7.0 release.
