### ISSUE TITLE
Auto-generated nodegroups have errors?

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#414]
I started a new 'dev' RACK image just now; it appears to be pre-populated with 'auto generated ingestion' entries.  One of these (ingest_TEST_EXECUTION) is being used by the GE data set, but it returns errors regarding the `http://arcos.acert/GrammaTech#memory` property. Similarly, loading this nodegroup from the newly started RACK image produces a related error, as shown in the attached image.

![image](https://user-images.githubusercontent.com/69644139/119722477-5b0ea880-be3a-11eb-9bb0-413d8dec1f28.png)

**Comment by kityansiu** [comment]
This has been fixed. A little background: we changed setup-rack.sh so that it no longer loads all the overlays. That shell script is used to build the docker image. Consequently, we also changed the way we auto generate the set of ingestion nodegroups.
