### ISSUE TITLE
Turnstile example needs a setup script

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#440]
Providing separate setup scripts for the core RACK ontology and the ARCOS overlays is a good idea, but for consistency, there should also be a setup script for the Turnstile example.

It would also be better if this script was described in the section  of the README on how to initialise the RACK rather than as an example of how to import data.

https://github.com/ge-high-assurance/RACK/tree/master/cli

**Comment by kityansiu** [comment]
We will have a turnstile load script like [this](https://github.com/ge-high-assurance/RACK/blob/TurnstileUpdate/Turnstile-IngestionScripts/Turnstile-IngestionPackage/Load-TurnstileData.sh)
