### ISSUE TITLE
RACK 7.0 - SPARQLGraph can't load nodegroups

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#452]
If you try and load a nodegroup from SPARQLGraph, you get the following error message:

```
Error: Error: belmont.js:SemanticNodeGroup.addJson() only recognizes nodegroup json up to version 12 but file is version 13
url: http://rack.office.adelard.com:8080/sparqlGraph/js/belmont.js
line: 1771
undefined
column: 181
error: Error: belmont.js:SemanticNodeGroup.addJson() only recognizes nodegroup json up to version 12 but file is version 13
```

**Comment by cuddihyge** [comment]
This means your javascript is old.
It most likely requires a  clearing of your cache (or hard-reload the SPARQLgraph page).
This is different for every browser.  Take a look at [Wiki: Bypass your Cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache)

If you are doing some kind of piecemeal download and running (i.e. not just running everything out of one Docker image) then it is possible you need to actually pull all the latest code, as things are out of sync.   This will also require a browser refresh.

We have searched but have not found a way to stop browsers to stop caching old javascript.  The solution is different for every browser.

**Comment by cuddihyge** [comment]
I would like to convert this to a discussion with a slightly cleaner title.   Discussion topics are useful as a question-answer database.  This is a recurring question that currently appears to be beyond our ability to fix any further.   @Robert-Adelard please accept the answer by clicking the checkmark, or let us know if this isn't a full answer.
