### ISSUE TITLE
Achieve 1hr ingestion on Boeing/Grammatech 2.6M relationship load

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#454]
Will depend on machine and configuration.
This seems to be CPU limited, so number of cores will be critical.
Try to achieve <1hr on a "standard laptop"

**Comment by cuddihyge** [comment]
This is now in the latest docker dev built around 11am 7/9/2021 Eastern
da1260f945294361682a0f74fcbd6cfd1ea7748e8b549fdac7a21b7f42f28412

**Comment by AbhaMoitra** [comment]
I tested the dev release. I was able to load in the GT data in 61 minutes (after GE data was loaded).

**Comment by AbhaMoitra** [comment]
Ingestion timing has been done by Dan, Eric, Abha.
