### ISSUE TITLE
Prevent SPARQLgraph from caching .js from previous release

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#455]
Trying some new cache-reduction code.
This will need a little testing when it goes into the next docker image.
Check the network traffic in the browser to see if the SHA is appended to each javascript file, and that it is the latest.
It still MIGHT require a hard refresh of the top page, but the Cache-control no-cache tag might handle that.

Also: fix error message in case this fails.  At least point out it is a likely caching issue in the message.

**Comment by Ptival** [comment]
Is this resolved?

**Comment by cuddihyge** [comment]
Yes. Note that it is in the "Done" section of Pre-Release 8.
