### ISSUE TITLE
Turnstile Example - missing data from DevelopmentPlanData

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#457]
Some of the entities defined in `Turnstile Ontology/00-Planning/DevelopementPlanData` (sic!) are missing from the RACK - it looks to me as though this file never gets loaded - in particular, it's missing from the `Data` folder, although it's present in `OwlModels`.

For example, I've been unable to find any of the `SoftwareXXXProcess` ACTIVITY objects defined in `DevelopementPlanData`.

Similarly, various artefacts generated by the software development process are missing, for example, `Counter-SW-Des` and `SW-Code`.

**Comment by Robert-Adelard** [comment]
Note that there is some overlap between `DevelopementPlanData`, which defines various system and software design artefacts, and `TurnstileSystemDesign` and `CounterApplicationDesignDescription`, which define the same artefacts - e.g. `Turnstile` and `InputThread`.

**Comment by Robert-Adelard** [comment]
`DevelopementPlanData` also defines various documents, but none of these appear to be loaded into the RACK. For example, I can find no instances of
```
DESCRIPTION
PLAN
PROCEDURE
REPORT
REQUEST
SECTION
```
and only two instances of `SPECIFICATION`.

**Comment by Robert-Adelard** [comment]
Another peculiarity of the `Turnstile` data set is that the single `HlrReview` activity generated three review logs for each requirement, which had different outcomes. Does this make sense, or should there be three separate review activities, one for each review log?

**Comment by kityansiu** [comment]
> Some of the entities defined in `Turnstile Ontology/00-Planning/DevelopementPlanData` (sic!) are missing from the RACK - it looks to me as though this file never gets loaded - in particular, it's missing from the `Data` folder, although it's present in `OwlModels`.
> 
> For example, I've been unable to find any of the `SoftwareXXXProcess` ACTIVITY objects defined in `DevelopementPlanData`.
> 
> Similarly, various artefacts generated by the software development process are missing, for example, `Counter-SW-Des` and `SW-Code`.

The updated Turnstile will have the `SoftwareXXXProcess` ACTIVITYs from `DevelopmentPlanData`. We also have the artifacts that wasGeneratedBy certain ACTIVITYs.

> 
> 
> `DevelopementPlanData` also defines various documents, but none of these appear to be loaded into the RACK. For example, I can find no instances of
> 
> ```
> DESCRIPTION
> PLAN
> PROCEDURE
> REPORT
> REQUEST
> SECTION
> ```
> 
> and only two instances of `SPECIFICATION`.

The updated Turnstile will have the instance data from `DevelopmentPlanData`. Note: we did not have instance data for PROCEDURE and REQUEST.
