### ISSUE TITLE
Shouldn't setup-rack.sh start with --clear ?

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#462]

**Comment by Robert-Adelard** [comment]
I think this would be a good idea too - currently, you have to go through quite a few steps to nuke your RACK and start again.

**Comment by glguy** [comment]
Neither `setup-rack.sh` nor `setup-arcos.sh` currently load any data. Removing data is currently done per data graph. Data graphs are chosen by the system ingesting the data. These two scripts populate nodegroups and ontology models. (It might make sense for these scripts to clear our the models when importing to them, though.)

The right place to clear out data graphs is probably in the ingestion scripts to load data in the first place.

**Comment by Robert-Adelard** [comment]
I think it would be useful to have an option to delete everything in the RACK - data, nodegroups, and ontologies - so that you can start again with an empty RACK.

**Comment by glguy** [comment]
@cuddihyge Is there a way to clear all model/data in SemTK without knowing the data graphs?

**Comment by cuddihyge** [comment]
No, most triplestores don't let you delete everyone else's data.    You'd have to go into fuseki and delete the dataset.

The functionality I think Robert and I were thinking about was at the **setup-rack.sh** or **setup-arcos.sh** level.   For me, any time I run those, I am starting over from scratch.  I don't want to load two copies of the models.  I ususally use the **Import** tab in SPARQLgraph to clear the data and model first.  

I guess it gets trickier with loading data, since we may load different datasets all into the same graph.

Perhaps a starting point would be a -clear option on the scripts or a clear-rack.sh script that clears any graphs we currently use.   Then we'll understand if we need something fancier.

**Comment by Robert-Adelard** [comment]
> The functionality I think Robert and I were thinking about was at the setup-rack.sh or setup-arcos.sh level. 

Yes, exactly - the requirement is to be able to empty the RACK and start again. That means deleting all the ontologies, nodegroups and data that has been loaded into any data graph that belongs to the RACK.

> Perhaps a starting point would be a -clear option on the scripts or a clear-rack.sh script that clears any graphs we currently use. 

Yes - this would be fine. Also, perhaps a warning if you try to load stuff that has already been loaded and not cleared out.

**Comment by glguy** [comment]
I've added a [setup-clear.sh](https://github.com/ge-high-assurance/RACK/blob/master/cli/setup-clear.sh) script that clears all the things I know to clear. There could be other data graphs populated in a RACK instance if another script happens to populate another data graph, but this covers the defaults.

**Comment by AbhaMoitra** [comment]
@glguy : was decided at last ontology meeting to assign this to you so you can close it out
