### ISSUE TITLE
ASSIST - Prolog documentation

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#472]
If I run the Prolog documentation server, as per the instructions here

https://github.com/ge-high-assurance/RACK/tree/master/assist/bin#prolog-api-usage

I get a series of errors as follows:

```
ERROR:  .../RACK/assist/bin/documentation/serve.pl:20:
ERROR:    import/1: No permission to import requirements:mitigates/2 into user (already imported from hazard)
ERROR: .../RACK/assist/bin/documentation/serve.pl:20:
ERROR:    import/1: No permission to import requirements:assert_author/2 into user (already imported from hazard)
ERROR: .../RACK/assist/bin/documentation/serve.pl:20:
ERROR:    import/1: No permission to import requirements:assert_mitigates/2 into user (already imported from hazard)
ERROR: .../RACK/assist/bin/documentation/serve.pl:20:
ERROR:    import/1: No permission to import requirements:author/2 into user (already imported from hazard)
ERROR: .../RACK/assist/bin/queries/hazard_structure.pl:18:
ERROR:    import/1: No permission to import requirements:mitigates/2 into hazard_structure (already imported from hazard)
ERROR: .../RACK/assist/bin/queries/hazard_structure.pl:18:
ERROR:    import/1: No permission to import requirements:assert_author/2 into hazard_structure (already imported from hazard)
ERROR: .../RACK/assist/bin/queries/hazard_structure.pl:18:
ERROR:    import/1: No permission to import requirements:assert_mitigates/2 into hazard_structure (already imported from hazard)
ERROR: .../Work/RACK/assist/bin/queries/hazard_structure.pl:18:
ERROR:    import/1: No permission to import requirements:author/2 into hazard_structure (already imported from hazard)
```

**Comment by Robert-Adelard** [comment]
Incidentally, since the Prolog ontology files are no longer included in the RACK distribution, as per

https://github.com/ge-high-assurance/RACK/commit/b90f96c4df07c8c72ab7b5b3c47e4cbd2e96f526

the instructions for running the documentation server should mention the need to auto-generate the ontology files.

**Comment by Ptival** [comment]
Indeed that's embarassing, hah Prolog!

I will see if I can conditionally list the ontology files based on whether they have been generated or not.

Will update.

**Comment by Robert-Adelard** [comment]
Thanks for looking into this - I ran into another problem today that might be related:

```
?- [assist/bin/ontology/prov-s].
ERROR: source_sink `assist/bin/ontology/prov-s' does not exist
ERROR: In:
ERROR:   [20] throw(error(existence_error(source_sink,...),_11088))
ERROR:   [16] '$resolve_source_path'(... / prov-s,_11120,[expand(true)]) at /opt/homebrew/Cellar/swi-prolog/8.2.4/libexec/lib/swipl/boot/init.pl:2318
ERROR:   [15] '$load_file'(... / prov-s,user,[expand(true)]) at /opt/homebrew/Cellar/swi-prolog/8.2.4/libexec/lib/swipl/boot/init.pl:2292
ERROR:    [9] <user>
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
?- [assist/bin/ontology/provs].
ERROR: import/1: No permission to import 'prov-s':entity/1 into user (already imported from rack)
true.
```

It looks as though SWI Prolog doesn't like modules names that include a minus sign - maybe they need to be quoted in some way.

As you can see, renaming the file solved the problem, and left me with the familiar `No permission` error.

**Comment by kquick** [comment]
In SWI Prolog the `consult(filename)` command (with alternate syntax `[filename]`) expects the `filename` portion to be an `atom`.  SWI Prolog will automatically interpret bare text as an atom, but if that atom contains special characters, it should be single-quoted to make the atom explicit.

For the case reported above, the syntax should be `['assist/bin/ontology/prov-s']`.
