### ISSUE TITLE
Turnstile ontology - property names should not begin with upper case

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#480]
The Turnstile ontology defined in `DevelopmentPlan.sadl` includes two properties whose names begin with upper case:

```
    StructualCoverageAnalysis is a type of ANALYSIS.
        CoveredNodes describes StructualCoverageAnalysis with values of type int.
        UncoveredNodes describes StructualCoverageAnalysis with values of type int.
```

This causes `write_ontology` in the ASSIST toolkit to generate invalid Prolog predicates (see #479 ), but is also inconsistent with the naming conventions used for the core RACK ontology.

**Comment by glguy** [comment]
@kityansiu Could this be incorporated into the turnstile update?

**Comment by kityansiu** [comment]
Fixed in this [commit](https://github.com/ge-high-assurance/RACK/pull/463/commits/bef0be4e7c993047f8b523fa6cdfe6160e2d6291)
