### ISSUE TITLE
Turnstile ontology should have an appropriate URI

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#487]
The Turnstile ontology has a URI prefix of `http://turnstile`, which means it isn't recognised by the `rack_lib` predicate in RACKLIB.

Moreover, this URI does not respect the de facto naming convention that has been adopted by other ontologies, namely `http://arcos.project/partner`.

See also #478 and #485 - hopefully, this will be addressed by #463.

**Comment by kityansiu** [comment]
Fixed in [GE.sadl](https://github.com/ge-high-assurance/RACK/blob/TurnstileUpdate/GE-Ontology/ontology/GE.sadl)
