### ISSUE TITLE
SPARQLGraph - behaviour of Query menu

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#491]
SPARQLGraph has a `Query` menu that lets you choose between `service layer` and `SPARQL endpoint`. The distinction between these two options is not immediately obvious, but the observed behaviour is different:

1. Selecting `SPARQL endpoint` disables the `Run` command for the node group
2. If you run a query via `SPARQL endpoint`, the first column of the result is sorted and has a blue header

I don't know if these differences are deliberate but the behaviour could be more consistent - for example, why is the `Run` button under `Query` not disabled if you select `service layer` and why is the output not sorted in the same way?

**Comment by cuddihyge** [comment]
This legacy feature should be removed.  It is indeed confusing.  And it is not useful.

**Comment by weisenje** [comment]
Removed the obsolete Query menu.
