### ISSUE TITLE
Run large PerformanceTests on fuseki

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#495]
100,000 "nodes" might be 4,000,000 triples
so 1M "nodes" might be 40M triples

Where does Fuseki become untenable?

Upgrade and run PerformanceTest standalone executable.

**Comment by cuddihyge** [comment]
@Ptival :  are you able to find a machine where you can run the performance tests up to 4M triples for starters?   Or should I return to hunting for a machine on my end.

**Comment by Ptival** [comment]
@cuddihyge I feel like we brought this up during a meeting, but never circled back.

Have you been able to find a machine for running performance tests that did not monopolize your workstation?

**Comment by cuddihyge** [comment]
Yes I'll do this.  It may not happen until I return from vacation on the 16th but I do not believe it is urgent.

**Comment by cuddihyge** [comment]
Results are uploaded to the Box Team Workspace under Paul and "3Q21 Performance Test" files.
Excel has raw results.
Word doc has a couple-page summary.

**Comment by cuddihyge** [comment]
I've moved the results out of my personal RACK box workspace to:
DARPA ARCOS RACK->9_Design->RACK_Performance
