### ISSUE TITLE
Learn and experiment with Jena TDB indices to see how performance can be tweaked.

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#496]
Start with these [jena docs](https://jena.apache.org/documentation/tdb/)

**Comment by cuddihyge** [comment]
It does not look like this is possible.

**Comment by AbhaMoitra** [comment]
Closing this issue as per team discussion on 11/9/2021.

**Comment by Ptival** [comment]
I did not catch why this is impossible. Is there a two-sentences summary of the problem?

**Comment by cuddihyge** [comment]
Fuseki seems to have full text search indices that are slightly customizable, but I could not find a mechanism for building an index to speed up plain SPARQL.   Everything is in the first sentence.
