### ISSUE TITLE
ASSIST - write_ontology should convert minus to underscore

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#499]
The PROV-S ontology is converted into a `prov-s` Prolog file, which needs to be quoted, as per #472.

This could be avoided if `write_ontology` converted the minus to an underscore, so that the generated filename was `prov_s`.

**Comment by kquick** [comment]
I appreciate the suggestion, but I think I'd prefer to maintain fidelity to the original naming scheme, even though it'll require specific quoting in some scenarios.  This will provide both consistency and avoid the need to address collisions that can occur as a result of the alpha renaming.  Is this OK for your needs or do you have a strong requirement to avoid the quoting?

**Comment by Robert-Adelard** [comment]
Hmm - I don't have a strong requirement to avoid the quoting, but if the names of the ontology files can include a minus, any general purpose script that took an ontology as a parameter would need to quote the file name to be on the safe side.

Mapping minus to underbar is a common convention, so I don't see a problem with consistency - I'm not sure I understand your concern about alpha renaming.

But it was just a suggestion to clean up a problem caused by the `PROV-S` ontology, so it's not a big issue either way.

**Comment by Ptival** [comment]
I also think I prefer avoiding mangling as much as possible so that we don't have to keep track of such decisions across projects. Will close for now, reopen if this ever becomes terribly inconvenient.
