### ISSUE TITLE
SPARQL Graph - clicking Clear on a relationship generates a Type Error

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#501]
If I click on on a relationship to bring up the dialog that lets me modify various properties such as Opt/Minus and then select Clear, I get a TypeError:

![image](https://user-images.githubusercontent.com/68293728/125159001-86402380-e16c-11eb-9fa8-2bbc1ba2369d.png)

**Comment by kityansiu** [comment]
Tested. Looks good!
