### ISSUE TITLE
SPARQL Graph - optimises away ENTITY_type for entity types that have no subtypes

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#505]
Select an entity type with no subtypes, for example `SoftwareThread`. Now select `identifier` and `SoftwareThread_type` to list all instances of software threads - SPARQL Graph constructs the following SPARQL query:

```
select distinct ?SoftwareThread_type ?identifier
		FROM <http://rack001/data>
		FROM <http://rack001/model>
where {
	?SoftwareThread a DevelopmentPlan:SoftwareThread .
	?SoftwareThread PROV_S:identifier ?identifier .
}
```

Note that there is no pattern to match `?SoftwareThread_type` so that result column for that property is blank.

It looks as though SPARQL Graph has incorrectly optimised away the term
```
?SoftwareThread a ?SoftwareThread_type
```
See also #493.

**Comment by cuddihyge** [comment]
closed with 493 fix
