### ISSUE TITLE
TURNSTILE example - missing links to DO-178C objectives

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#506]
`00-Planning/DevelopementPlanData.sadl` (sic!) includes a number of rules that are supposed to map Turnstile development activities onto DO-178C objectives. However, not all of these rules are being applied.

In particular, `HlrReview` is a `SoftwareRequirementsReview` and should be mapped onto the DO-178C A-3 objectives.

Similarly, the various test runs should be mapped onto A-6 and A-7 objectives.

As far as I can tell, these rules are not being applied because the nodegroup for `OBJECTIVE` does not include the relevant Turnstile `ACTIVITY` types , specifically `SoftwareRequirementsReview, SoftwareUnitTestExecution` and `SoftwareComponentTestExecution`.

**Comment by Robert-Adelard** [comment]
There are also some rules for `DataCouplingAnalysis` and `ControlCouplingAnalysis` - however, the Turnstile example does not include any examples of these analyses, so the rules aren't triggered.

**Comment by kityansiu** [comment]
This is now fixed in the branch, under Turnstile-IngestionScripts/Turnstile-IngestionPackage/Objectives.
