### ISSUE TITLE
SPARQL Graph - another ENTITY_type bug

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#509]
Consider the following nodegroup query:

```
select the review type, id and entity type, id for all entities that have been reviewed
```

SPARQL Graph converts this into SPARQL as follows:

```
select distinct ?REVIEW_type ?identifier ?ENTITY_type ?identifier_0
		FROM <http://rack001/data>
		FROM <http://rack001/model>
 where {
	?REVIEW a ?REVIEW_type .
	VALUES ?REVIEW_type { REVIEW:REVIEW DevelopmentPlan:SoftwareRequirementsReview DevelopmentPlan:SoftwareCodeReview DevelopmentPlan:SoftwareDesignReview  } .
	?REVIEW PROV_S:identifier ?identifier .
	?REVIEW REVIEW:reviewed ?ENTITY .
		?ENTITY PROV_S:identifier ?identifier_0 .
}
```
Note that there is no binding for `?ENTITY_type`, so no entity types are returned - the following clause is missing:
```
?ENTITY a ?ENTITY_type
```
See also #493 and #505 - this may be a related bug.

**Comment by cuddihyge** [comment]
We've established ( #493 ) that there is a bug where the _type is dropped for a node with incoming connections that determine the node's type.   A fix will be in the next release.    This has been reproduced, so no further examples are needed.
