### ISSUE TITLE
SPARQL Graph - loses entity properties in UNION query

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#513]
This looks like a bug - what has happened to the third `LowLevelRequirement` entity?

![image](https://user-images.githubusercontent.com/68293728/126521362-ace34665-02fd-40a2-a043-cbc71abcc5f4.png)

**Comment by cuddihyge** [comment]
duplicate issue

**Comment by Robert-Adelard** [comment]
See #516 - in this case, it is possible that I did click on the minimise button by accident, but #516 is reproducible.
