### ISSUE TITLE
SPARQL Graph truncates entity class

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#516]
This looks like a bug - what has happened to the third `LowLevelRequirement` entity?

![image](https://user-images.githubusercontent.com/68293728/126521362-ace34665-02fd-40a2-a043-cbc71abcc5f4.png)

**Comment by Robert-Adelard** [comment]
The bug is easy to reproduce - just shift drag three `TEST` objects onto the canvas.

However, I've not been able to recreate the screen image above, in which a `LowLevelRequirement` object has been truncated.

**Comment by cuddihyge** [comment]
You have clicked on the minimize button in the top bar (the __ ) .  In order to restore it, click on the box.
It works similar to Windows.

**Comment by Robert-Adelard** [comment]
@cuddihyge No I haven't - for reasons best known to itself, SPARQLGraph has decided to minimise the third instance of a TEST, but I certainly haven't done this. I didn't even realise it was possible to do so, but thanks for the explanation.

Please re-open this issue.

**Comment by cuddihyge** [comment]
I have pushed a fix.  It may not hit -dev docker until early August (lower priority)

**Comment by Robert-Adelard** [comment]
> I have pushed a fix. It may not hit -dev docker until early August (lower priority)

Thanks - it's not exactly critical...
