### ISSUE TITLE
Remove "inverse" relationships in SYSTEM.sadl

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#522]
We have 2 pairs of inverse relationships in SYSTEM.sadl (source is inverse of provides and destination is inverse of requires). The domain and range for these 2 pairs are such that they are not inverses. And since we do not really use (or enforce) the inverse property, it was decided to drop both of these inverse relationships.

**Comment by Ptival** [comment]
Related to PR https://github.com/ge-high-assurance/RACK/pull/523
