### ISSUE TITLE
Turnstile example - ingestion queries don't follow RACK naming convention

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#525]
The Turnstile ingestion queries are named "Ingest-ENTITY" rather than "ingest_ENTITY" so they are not deleted by the `setup-rack.sh` script when it runs
```
rack nodegroups delete --yes --regexp --ignore-nonexistent "^ingest" "^query"
```
(Note the different capitalisation and the use of dash rather than underbar)

**Comment by kityansiu** [comment]
This has been fixed in the branch.
