### ISSUE TITLE
SPARQLGraph - upload nodegroup does not prompt to save or discard 

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#527]
If you upload a nodegroup, you are not prompted to save it.

If you upload another nodegroup, you are not asked if you want to discard the previous nodegroup

The net result is that you upload a series of nodegroups, expecting them to be saved automatically, and nothing happens.

**Comment by Robert-Adelard** [comment]
Also, if you do save a nodegroup that you have uploaded, you are prompted to save it under the name of the previous nodegroup you saved, not the name of the nodegroup you uploaded - in other words, the name and comment in the nodegroup you uploaded are ignored.

**Comment by cuddihyge** [comment]
Regarding the prompting to save:  SPARQLgraph only prompts you to save if you've made a change.  There is no presumption that things need to be saved to the store (sometimes it is best to keep them on disk).

Regarding the save name, it is also often "normal" to work on a certain nodegroup in the store and pull in a version from disk.
Please clarify ```the name and comment in the nodegroup you uploaded are ignored``` as I'm not sure what name and comments you mean.

**Comment by cuddihyge** [comment]
Based on other bug fixes and UI updates, dragging a nodegroup from disk replaces the "name" with a cleaned-up version of the file name.  This fixes the "bug" portion of this issue.

**Comment by cuddihyge** [comment]
Now that dragging a nodegroup onto SPARQLgraph displays the filename on top of the canvas, the "save to store" dialog needs to prefill the "Id" field.
