### ISSUE TITLE
SPARQLGraph - saving a node group under a different name

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#528]
If you load a nodegroup and then save it under a different name, SPARQLGraph still displays the original name, even though it remembers the new name

**Comment by Robert-Adelard** [comment]
Saving a nodegroup under a different name and then deleting the original nodegroup is the only way to rename a nodegroup - it would be better if there was a rename nodegroup option.

**Comment by Robert-Adelard** [comment]
Please could you add a `bug` label too - the current behaviour is confusing / wrong. Thanks.

**Comment by cuddihyge** [comment]
Fixed these issues:   

- nodegroup store dialog keeps row highlighted after rename.  (You can screw this up with a diabolical use of the column filters, but within reason things work)
- button states in the nodegroup store dialog are correct
