### ISSUE TITLE
`employedBy` in `AGENTS.owl` does not list its domain/range explicitly

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#545]
I was trying to inspect our OWL files programmatically and ran into some oddity where some OWL tooling things `PERSON#employedBy` has an empty domain and an empty range.

It turns out that the OWL file for it looks like:

https://github.com/ge-high-assurance/RACK/blob/42ceaff2d4c837e766d5481599a4ab94556255a2/RACK-Ontology/OwlModels/AGENTS.owl#L48-L51

with no `rdfs:range` or `rdfs:domain`. This appears to be one of the only object property to ever look like this.

SPARQLGraph seems to use:

https://github.com/ge-high-assurance/RACK/blob/42ceaff2d4c837e766d5481599a4ab94556255a2/RACK-Ontology/OwlModels/AGENTS.owl#L37-L44

to infer the range, but I'm not sure how common that is.

---

It seems like it's a mix of it being `a type of actedOnBehalfOf` and being `at most one value` that makes it generate such OWL.

Contrast with `CONFIDENCE#performedBy`, also `a type of wasAssociatedWith` but generates a domain/range.

Contrast with `PROV-S#dataInsertedBy`, also a `at most one value` but generates a domain/range.
(Also, does the OWL ever change for "at most one value"? Does not look like it does.)

Any idea why @cuddihyge ?

**Comment by cuddihyge** [comment]
SADL-to-owl is outside my expertise.  
I think we'll need to ask @AbhaMoitra  and @agabaldon look at how SADL is generating the owl.

**Comment by AbhaMoitra** [comment]
This is indeed very strange. I'll post it on SADL GIT to get an answer / explanation and then I'll post here with what I learn.

**Comment by AbhaMoitra** [comment]
Andy Crapo replied to my post in the SADL GIT, please visit https://github.com/SemanticApplicationDesignLanguage/sadl/discussions/772 and we can follow-up on this there. Again, thanks @Ptival for identifying this.

**Comment by Ptival** [comment]
The discussion over there seems to suggest that we should change:

https://github.com/ge-high-assurance/RACK/blob/5ef4f73709136ea15bd2d5f80420d260bea2e319/RACK-Ontology/ontology/AGENTS.sadl#L35-L36

to instead read something more like the following:
```
 employedBy (note "Relates people to the company they were acting on behalf of.")
  describes PERSON with valus of type AGENT.
 employedBy describes PERSON with at most 1 value of type AGENT.
```

where:
- the duplication of the declarations is important to ensure the `domain`/`range` gets acknowledged in OWL,
- and the use of the digit `1` instead of the word `one` is necessary so that the cardinality constraint is actually present in OWL.

I am currently unable to run SADL on my machine (cf. https://github.com/SemanticApplicationDesignLanguage/sadl/issues/646 ), so if we validate those changes, someone should go ahead and update the SADL and OWL files if they can!
