### ISSUE TITLE
Turnstile's `DevelopementPlanData` should be called `DevelopmentPlanData`

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#546]
Just a typo.

**Comment by kityansiu** [comment]
Similar to issue #547, what was in TurnstileOntology\00-Planning\DevelopementPlanData.sadl will be replaced with the CDRs in Turnstile-Example\Turnstile-IngestionPackage\TurnstileDevelopmentPlanData when we merge the TurnstileUpdate branch (PR #463).
