### ISSUE TITLE
Should `TurnstilesSystemDesign` be called `TurnstileSystemDesign`?

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#547]
Not sure whether the `s` in the name is voluntary.

**Comment by kityansiu** [comment]
The directory Turnstile-Ontology will be removed when we pull in the TurnstileUpdate branch. The information in the file TurnstilesSystemDesign.sadl will be replaced with the CDRs that will be in Turnstile-Example\Turnstile-IngestionPackage\TurnstileSystemDesign.
