### ISSUE TITLE
SRI ontology - typo in GenericProperty verficationObjective (sic!)

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#552]
The `verficationObjective` property of `GenericProperty` should be spelled `verificationObjective`.

See also "tool verfication procedures" in the note on `ToolQualificationData`.

**Comment by AbhaMoitra** [comment]
Corrected as part of the merge of analysis_enhancement branch.

**Comment by AbhaMoitra** [comment]
Corrected as part of merge of analysis_enhancement branch.
