### ISSUE TITLE
add TEST_PROCEDURE to the core ontology

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#573]
From [Summary-Learnings, Gaps, Enhancements](https://github.com/ge-high-assurance/RACK/wiki/Summary-Learnings,-Gaps,-Enhancements):

> [Adelard] DO-178C distinguishes between a Test case and a Test procedure. Roughly speaking, a Test case is the specification of a test and a Test procedure is an implementation of a test – logically, these are not the same thing.

> [SRI] Test Obligations, Test Cases, and Test Procedures: There is a single class TEST in RACK that is not sufficient to capture the attributes semantics across all the testing-related entities, as others have also noted. It would help to use generic guidance from DO-178C here. In Do-178C, a test case is an abstract specification that consists of test criteria for requirement coverage (i.e., what aspect of requirement clause/subclause does the test cover), test description, trace to the requirement or to test obligation (oracle), test inputs values and expected output values applied to the component under test. A test procedure is typically a script that applies the input values to the component, measures output values and compares them to expected outputs of test case. One may merge test case and procedure as long as all the relevant semantics are captured; but the TEST class in RACK doesn’t have those attributes.

This was discussed at the Data Model Decision Team Meeting on 10/25/21. We will look into including Test Procedure in the core ontology.

**Comment by AbhaMoitra** [comment]
At the team meeting on 11/9/2021 we also decided to ad PARTITION as part of this.
