### ISSUE TITLE
add installation configuration to ontology

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#574]
From [Summary-Learnings, Gaps, Enhancements](https://github.com/ge-high-assurance/RACK/wiki/Summary-Learnings,-Gaps,-Enhancements):

> [SRI]  Tool installation and qualification data: Besides the tool version, the actual installation configuration of the tool on a particular PC/OS is essential to establish confidence that the tool invocation produces correct results. The tool installation instructions must come with the installation configuration/verification checklist that should be filled in for this purpose when the tool is installed. Also, tool qualification data (pertaining to the particular tool version) must be included in the evidence

Will be in Release 9.0.

**Comment by AbhaMoitra** [comment]
Done as part of analysis_enhancement branch and it has been merged with the master.
