### ISSUE TITLE
to support property-based assurance in ontology

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#575]
From [Summary-Learnings, Gaps, Enhancements](https://github.com/ge-high-assurance/RACK/wiki/Summary-Learnings,-Gaps,-Enhancements):

> [SRI]  GenericProperty and SpecificProperty: To use formal methods for verification and for property-based assurance in general, we added these two classes to give property a first-class status with relationships such as propertyScope and propertyBasis. Then a property can be analyzed by many activities independently.

Plan to have this in v9.0.

**Comment by AbhaMoitra** [comment]
Done as part of analysis_enhancement branch and it has been merged with the master.
