### ISSUE TITLE
Handle Range restrictions in SemTK

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#596]

**Comment by cuddihyge** [comment]
I'll need some help with this from @AbhaMoitra et. al. on better organizing and defining this task.

#1  for datatype restrictions (e.g. DAL is a type of int [0,9]. ) help assembling a full definition of what SADL allows for restrictions.

#2 for range restrictions on object properties
       a. split to another issue
       b. again, what is legal (e.g. only specfiic sub-type(s) of the parent definition),  can they be complex (e.g. parent says range is Animal, and subtype says Dog or Cat or Mouse)
       c. should we hunker down and do the whole complex Range of data properties first.   Several week effort, but Jan-Feb 2022 might be an opportune time to tackle it.

**Comment by AbhaMoitra** [comment]
@cuddihyge : Sure. Can you set up a call to discuss this.

**Comment by AbhaMoitra** [comment]
SparqlGraph is throwing an error when we tried to correct a nodegroup where it is using the parent of the correct class. @cuddihyge has an example.

**Comment by cuddihyge** [comment]
I believe this was fixed in semtk commit March 11  e5fb84bb468863daecd687f1976c0c7349316689 
which went into semtk release 03/11 and RACK 10.0.
