### ISSUE TITLE
Duplicate performedBy properties in SOFTWARE

### ISSUE THREAD

**Issue by kquick** [ge-high-assurance/RACK#607]
In RACK-Ontology SOFTWARE.sadl, we have the following:

```
COMPILE
    ...
    sw:performedBy (note "AGENT(s) (e.g. COMPILER) performing the compilation") describes COMPILE with values of type AGENT.
    sw:performedBy is a type of wasAssociatedWith.

PACKAGE
    ...
    sw:performedBy (note "AGENT(s) (e.g. PACKAGER) performing the packaging") describes PACKAGE with values of type AGENT.
    sw:performedBy of PACKAGE must be one of {Ag:PERSON, Ag:ORGANIZATION}.
    sw:performedBy is a type of wasAssociatedWith.
```

The duplicated property name is not distinguishable by domain, so these are really just a single property and not two separate properties.  The single property has three `rdf-schema#comment`, and an `rdf-schema#domain` of the `owl#unionOf` `SOFTWARE#COMPILE` and `SOFTWARE#PACKAGE`.

The `PACKAGE` instance adds an additional constraint that is propagated to the global property definition and therefore affects the COMPILE domain as well.  This is also called out by the ASSIST `check` tool:

```
Error: instance property http://rack001/turnstiledata#n1638223234-16641~tar . rack:SOFTWARE#performedBy of http://rack001/turnstiledata#User~root should be one of [http://arcos.rack/AGENTS#PERSON, http://arcos.rack/AGENTS#ORGANIZATION] but is a rack:PROV-S#AGENT`.
```

Note that https://github.com/ge-high-assurance/RACK/commit/7d2fe55f224207ffca0287c153369acd9fdb962e#diff-e3b1b6eea10a22f63d8cae0cfa850139622cce4814c6c3b31fdf6fc183c9df53L40-L41 just recently removed a third instance of this `performedBy` property, but all three properties still appear at:

https://github.com/ge-high-assurance/RACK/blob/master/ScrapingToolKit/AutoGeneration/table.csv#L582
https://github.com/ge-high-assurance/RACK/blob/master/ScrapingToolKit/AutoGeneration/table.csv#L595
https://github.com/ge-high-assurance/RACK/blob/master/ScrapingToolKit/AutoGeneration/table.csv#L637

As one possible fix, we could remove the `performedBy` from both `COMPILE` and `PACKAGE` and simply use `wasAssociatedWith` (and determine how to update the ScrapingToolKit `table.csv`).

**Comment by kquick** [comment]
Another (better?) fix would be to move `performedBy` to `ACTIVITY` and consistently have the distinction between "used" v.s. "initiator".

Regardless, our decision should be documented in the forthcoming user's guide (https://github.com/ge-high-assurance/RACK/tree/userguide)

**Comment by tuxji** [comment]
No matter which decision is taken, please make sure that `Turnstile-Example/Turnstile-IngestionPackage/CounterApplicationUnitTesting/ontology/CounterApplicationUnitTesting.sadl` uses the agreed-upon relations too.  I have #600 waiting to be merged which updates the relations in that file but you may need to update that file again.
