### ISSUE TITLE
Handle subranges of class int in SemTK

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#629]
In CPS.sadl we want to use

     DAL is a type of int [0,9]. 

Currently this is not being handled in SemTK. Once this is done we should be able to update DAL and ResidualRisk in CPS.sadl. We may also want to refine severity and likelihood in HAZARD.sadl.

**Comment by cuddihyge** [comment]
I'd like to split this.
On this issue, I will support Datatype and onDatatype, which is how SADL writes owl for the line. `DAL is a type of int`

The range restriction `[0-9]` will be handled separately as part of https://github.com/ge-high-assurance/RACK/issues/596

**Comment by cuddihyge** [comment]
Handling the range restriction as part of issue #643

**Comment by cuddihyge** [comment]
Currently handling these, and checking the restrictions during ingestion.
Test file passes on these:

```
over12 is a type of int [12,]. // an int >= 12
clothingsize is a type of {int or time or date}. // expanded to three types.  got rid of string because it catches everything
enumeratedheight is a type of string {"short", "medium", "tall"}. // enumeration of 3 possible string values
finger is a type of int {1,2,3,4,5}.
SSN is a type of string "[0-9]{3}-[0-9]{2}-[0-9]{4}".
year is a type of int [0,6]. // length 4 .
Airport_Ident is a type of string length 1-4 .
weight is a type of float [50,98.6).
```

Note that length of an int is commented out.  Andy has this example in his docs, but the owl did not generate properly, and I don't think this is too important of an example, since it would be better to say "is a type of int [1000,9999]"

**Comment by cuddihyge** [comment]
Dan found a bug.  This broke runtime constraints in SPARQLgraph.
I'll move back to "in progress and fix it"
