### ISSUE TITLE
CSV output from SPARQLgraph using incorrect escape characters

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#654]
When the text string has a quote or a newline then the resulting csv file downloaded from a query uses incorrect escape characters. This was shown to the sub-team on 2/2/2022 on Boeing data. This issue may be related to #650 : SPARQLgraph adds newlines when downloading CSV (https://github.com/ge-high-assurance/RACK/issues/650).

**Comment by cuddihyge** [comment]
See #650 for all notes.
