### ISSUE TITLE
Possible improvements for 'construct' queries

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#664]
I've made a couple of observations while playing with construct queries.
1. If an entity has attached non-entity properties, and you remove the entity, you can no longer remove the property. However, if you do things in the other order, it's possible to remove the property first, and then the entity.
2. When hovering over an entity, its SEMTK URI (UUID) is displayed. It would be substantially more useful if the _identifier_ could be displayed, given that the URI is randomly generated, and the identifier is quite meaningful given that you can already see what entity type is being referenced.

**Comment by GregIthaca** [comment]
For (1) I will have to get a RACK instance running with non-ITAR data, which might not happen before the holiday.
For (2) I apologize for not really knowing which portions of this are ARCOS/RACK specific and which ones are part of some more general purpose tooling. Maybe you don't actually own/maintain SPARQLgraph? However, if whoever owns this tooling is interested, perhaps this could be solved by having a "field of interest" parameter in SPARQLgraph that references the URI/UUID by default/when not set, but allows you to specify a preferred field for your particular instance? This would leave the behavior unchanged for all existing users while allowing it to be customized for the ARCOS RACK.

**Comment by chrisage** [comment]
Addressed
