### ISSUE TITLE
Range restriction bug: property shows twice

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#670]
Kit has found that with the range restrictions in Turnstile, some properties show up twice in SPARQLgraph and possibly it allows a nodegroup that violates a restriction.

E.g. wasInformedBy  of  SoftwareConfig and many others.

Related to #596

**Comment by cuddihyge** [comment]
@kityansiu 

When I add this test case: 
![image](https://user-images.githubusercontent.com/19863188/157515948-1d45cd46-b804-437f-955c-6ded79b545eb.png)

Notice the warning in sadl.  It says:
![image](https://user-images.githubusercontent.com/19863188/157516323-4797e2e2-7015-4a28-97c8-634a079235a7.png)

And then SADL generates *isRestricted* properly but does nothing with *isExpanded*, as demonstrated by this obscure new Explore feature in SPARQLgraph.  Here are the triples:
![image](https://user-images.githubusercontent.com/19863188/157516577-cd2c0d76-18f0-4c7c-95c8-1a42291000f3.png)

In this picture *_:b14* is a new restriction on *isRestricted* for the class *SubAnother*.    There is nothing in the ontology indicating the *isExpanded* has any changes when it's domain is *SubAnother*, so that line of SADL was ignored.

**Comment by cuddihyge** [comment]
So this doesn't solve much.  I'm essentially documenting carefully in case we need to ask Andy.

**Comment by cuddihyge** [comment]
I've discovered that at least for *wasInformedBy* (which exhibits the behavior of showing up twice, once with a range ACTIVITY and once with a super complex range) there seems to be a model problem.

There are two properties called *wasInformedBy* one in turnstile and one in PROV-S.   You can see this by hovering over the property in SPARQLgraph.

If this is in fact a SADL prefixing error of some kind, then I don't see a problem with SemTK (yet) except that ridiculously wide display when it tries to show the super complex range.

Tossing this over to you @kityansiu before I take any further action.

**Comment by kityansiu** [comment]
Okay! I will take a close look over our turnstile overlay file (GE.sadl).

**Comment by kityansiu** [comment]
I can confirm that after fixing the model in GE.sadl so that 1) I'm not defining a new property in the overlay; 2) the range of the property is restricted correctly, SemTK gives me the complex range I expected (and without the duplicate _wasInformedBy_).

<img width="776" alt="image" src="https://user-images.githubusercontent.com/12802455/157532468-702569f8-c4c1-4bff-9477-ac86401ebdb8.png">

**Comment by cuddihyge** [comment]
Perfect.  I'll move to "done" in case we want to review with anyone before closing.
