### ISSUE TITLE
for consideration: less prescriptive core; leave that for the overlays

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#674]
For consideration: should we be less prescriptive in the core ontology and leave it to the overlays to define more specific classes? For example, here's currently what's in the core for the property _wasGeneratedBy_

![image](https://user-images.githubusercontent.com/12802455/157920814-0f9e3dca-325d-48f5-a8f5-6a2aade00480.png)

For example, would it make sense to remove the line in SYSTEM.sadl that says 
`wasGeneratedBy of SYSTEM only has values of type SYSTEM_DEVELOPMENT`
This way, _wasGeneratedBy_ remains an ACTIVITY, unless it is further refined in an overlay that they should be of class SystemDevelopment.

**Comment by chrisage** [comment]
data model changes at this point would risk data integrity / backwards compatibility
