### ISSUE TITLE
Turnstile Data ingestion issue

### ISSUE THREAD

**Issue by saratge** [ge-high-assurance/RACK#690]
Followed all steps found in turnstile instance data ingestion at : https://github.com/ge-high-assurance/RACK/tree/master/Turnstile-Example/Turnstile-IngestionPackage

The final step of running Load-TurnstileData.sh runs into problems for both rack-box v10.0 and dev

Attaching screenshot

![turnstile data ingestion error](https://user-images.githubusercontent.com/98990225/162541148-2e10e7dd-60f8-4878-a9ca-75f299cd6c6b.PNG)

**Comment by saratge** [comment]
generating nodegroups using IngestTemplateGenerator and uploading them, resolves the issue
all the csv data goes through,  fails at the last step trying to ingest turnstile-ingest.rack

**Comment by baoluomeng** [comment]
It looks like someone has to update the nodegroups for Turnstile on SemTK. @kityansiu  @tuxji

**Comment by saratge** [comment]
works on an ubuntu machine, looks like my WSL is messed up
