### ISSUE TITLE
Use uniform notation in SOFTWARE.sadl and HARDWARE.sadl

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#691]
At the 4/19/2022 team meeting, it was decided to make the following changes to the Core Ontology for uniformity.

- In SOFTWARE.sadl change COMPONENT_TYPE to SWCOMPONENT_TYPE.
- remove subcomponentOf in SOFTWARE.sadl
- add partOf to appropriate classes in SOFTWARE.sadl and HARDWARE.sadl

Run ASSIST checks and SemTK reports to assess impact on nodegroups from these changes and communicate them.

These changes will mean that the changes that Devesh wants to make to the SRI overlay ontology (email of 4/19/2022) are not needed.

**Comment by kquick** [comment]
With the changes merged from PR #693 I now get the following issues reported from ASSIST:

> $ assist/bin/check
> Warning: No Note/Description for class http://arcos.acert/MITRE-CWE#CWE_EFFECTIVENESS
> 
> Warning: http://arcos.rack/SYSTEM#SYSTEM http://arcos.rack/MIL-STD-881D/MIL-STD-881D-AppxA#AircraftSystem-1 (AircraftSystem-1^^http://www.w3.org/2001/XMLSchema#string) missing the http://arcos.rack/SYSTEM#partOf target of type http://arcos.rack/SYSTEM#SYSTEM
> 
> Warning: http://arcos.rack/SYSTEM#SYSTEM http://arcos.rack/MIL-STD-881D/MIL-STD-881D-AppxB#ElectronicSystemGenericSystem-1 (ElectronicSystemGenericSystem-1^^http://www.w3.org/2001/XMLSchema#string) missing the http://arcos.rack/SYSTEM#partOf target of type http://arcos.rack/SYSTEM#SYSTEM
> 
> Warning: http://arcos.rack/SYSTEM#SYSTEM http://arcos.rack/MIL-STD-881D/MIL-STD-881D-AppxC#MissileOrdnanceSystem-1 (MissileOrdnanceSystem-1^^http://www.w3.org/2001/XMLSchema#string) missing the http://arcos.rack/SYSTEM#partOf target of type http://arcos.rack/SYSTEM#SYSTEM
> 
> Warning: http://arcos.rack/SYSTEM#SYSTEM http://arcos.rack/MIL-STD-881D/MIL-STD-881D-AppxD#StrategicMissileSystems-1 (StrategicMissileSystems-1^^http://www.w3.org/2001/XMLSchema#string) missing the http://arcos.rack/SYSTEM#partOf target of type http://arcos.rack/SYSTEM#SYSTEM
> 
> .................................. Summary ...................................
> Checked 69 core ontology classes, 28 overlay ontology classes, and 570 data instances
> Warning: There are 1 RACK definitions missing a Note/Description.
> Warning: There are 4 RACK SYSTEM issues.
> 5 ISSUES FOUND IN CHECK
> $

**Comment by AbhaMoitra** [comment]
@kquick : Not sure I understand the issues flagged by ASSIST. In the ontology we have the following 

![image](https://user-images.githubusercontent.com/28540315/164711540-9a90b9d5-ca6e-411d-9b7a-39888ee68a50.png)

and partOf is defined as follows - so we do not need to have partOf defined for a SYSTEM (in fact the top most system will not be part of anything else)

![image](https://user-images.githubusercontent.com/28540315/164711984-6f869b5c-a4cc-481b-8a4a-c3192848119d.png)

**Comment by kquick** [comment]
These ASSIST outputs are warnings, indicating something that is potentially a concern, but not definitively an error.

In this particular case, it's indicating that those 4 instances (AircraftSystem-1 and  the others) have no `partOf` target, which is the case as you noted.  Since there's no cardinality information provided, ASSIST doesn't have enough information to know if this is OK or not, so it's generating a warning  that this is something  the user might want to look into.

We can ignore these warnings as an intended data instance set, or we can provide cardinality information to clarify the relationship.

**Comment by AbhaMoitra** [comment]
@kquick. Thanks. So as a refinement of ASSIST, could we drop these "potential concerns" since there is no cardinality restriction supplied, it does not need to be present?
