### ISSUE TITLE
LM "string query" is very slow - Optimize

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#718]
- [x] demonstrate fuseki statistical optimizer
- [x] have Blazegraph demo for pheonix  (including CONSTRUCT)

RE:  **query_certgate_TopLevel-Claims-from-AcertReqModels**  in v10.2 against all three data graphs
```
		FROM <http://rack001/mitre-cwe>
		FROM <http://rack001/nist-800-53>
		FROM <http://rack001/model>
```

Separate from the fact that the query is bad.  It is slow.
1) can we further investigate the jena query optimizer
2) are there any changes to sparql generation

**Comment by cuddihyge** [comment]
@ptival I could use another pair of eyes on the optimizer, as I haven't been able to convince myself it does anything.

I have downloaded apache-jena-4.4.0 and gotten the .bat files to work.  (can't get the bash versions to resolve jars!)

I've done this:
```
cd whatever/run/databases/RACK
C:\Users\200001934\apache-jena-4.4.0\bat\tdbstats --loc=.  --graph urn:x-arq:UnionGraph > temp.opt
move temp.opt to stats.opt
```

And I've run different versions of the query with different optimizations based on [tdbstats quickstart docs](https://jena.apache.org/documentation/tdb/optimizer.html#quickstart)

But I can't convince myself anything slows down or speeds up the query.   Are you willing to take an independent shot at this?

**Comment by cuddihyge** [comment]
I do not believe SemTK should do a lot of optimization in its query generator since triplestores are supposed to do this and they all do it differently.

I have found that:
* the new sparql-gen branch randomly chooses to generate the SPARQL "islands" in the opposite order and performance is much better.   As above, I don't think Semtk can/should determine the order.  I hope we could get the optimizer to help(?)
* when a type clause includes a VALUES clause, it works faster to put the VALUES clause first.  this is sensible so I will change it.  Down-select the ?Node_type first before issuing a triple "?Node a ?Node_type" which could match every instance in the triplestore!
- 

-

**Comment by cuddihyge** [comment]
Tried Blazegraph.   It crashes on one of the newer auto-generated SemTK queries that retrieves the ontology.   Sigh.   Opened an issue on the Blazegraph github.

Aborted mission to test Blazegraph.

Query that fails is in ontologyInfo.java   "select distinct ?Property ?Domain ?Range ...."

**Comment by cuddihyge** [comment]
Fixed SemTK to work with **Blazegraph** and the LM query now returns in a **few seconds**.
Note that time to load the ingestion package is longer.
Also note that this is still a terrible query.

But we do have (opensource!) Blazegraph as a backup when we see performance problems.  There are many additional performance optimizations on Blazegraph that I have not tried.

**Comment by cuddihyge** [comment]
Will open two other small-ish issues to maintain SemTK and RACK cli compatibility with Blazegraph

**Comment by cuddihyge** [comment]
We can't use Blazegraph without downloading and compiling with the Log4j issue fixed.  This seems like a bad idea.  

However Blazegraph's fast execution of the query does prove that Apache Jena Fuseki is doing something very very sub-optimal.

**Comment by Ptival** [comment]
To be more precise, the optimizer gets thwarted by the presence of any `FROM` clause (even just one, unfortunately).

I will think about whether there is a solution for (1) that does not involve doing lots of graph-scoping in the query. I agree with you that wrapping every single clause ought to work, but that sounds unpleasant.

**Comment by cuddihyge** [comment]
We created a longer term #737 issue :   can /should  SemTK try optimizing using predicate counts

**Comment by cuddihyge** [comment]
I now have a local version of SemTK (which I will check in eventually since it is stable and low risk) that accepts the graph "**urn:x-arq:DefaultGraph**" as the default graph in any connection string.
The sparql generator will not generate a FROM or USING clause if a connection only references the default graph.
This will allow us to run some tests.

**Comment by cuddihyge** [comment]
I've also hacked a local copy of the rack cli (which I most definitely will **NOT** check in) that 
- forces all connections to the default graph
- skips any attempted clear

This allows me to run any ingestion scripts without modification and it all goes to the default graph.

Next step:  run some query tests and optimizations

**Comment by cuddihyge** [comment]
@Ptival I got it to work (!)

Loading everything into default graph at @Ptival 's instruction leads do a reduction **from 45 sec to 8 sec**.
Running tdbstats to RACK/Data-0001/stats.opt reduces further to **sub 1 sec**.

**Comment by cuddihyge** [comment]
Summary of how I needed to get this working
```
# First load into default graph, then:
$  export JENA_HOME=~/apache-jena-4.5.0
$  export PATH=$PATH:$JENA_HOME/bin
$ cd $JENA_HOME/lib
$  java -cp "*" tdb2.tdbstats --loc ~/apache-jena-fuseki-4.5.0/run/databases/RACK > ~/apache-jena-fuseki-4.5.0/run/databases/RACK/Data-0001/temp.opt
$ cd ~/apache-jena-fuseki-4.5.0/run/databases/RACK/Data-0001
$ mv temp.opt stats.opt
```

Changes we'd need to make to get this all working:
- Semtk handle default graph [cleanup, check-in]
- manifest override or other method to load everything into default graphs without copy-paste all load scripts
- include apache-jena jar (in addition to apache-jena-fuseki) in the docker container
- GUI button to optimize currently loaded data:
    - shut down fuseki
    - run tdbstats as shown above
    - restart fuseki
