### ISSUE TITLE
RACK GUI (config w/o python venv)

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#725]
- [x] try installing the eclipse plug-in and have a team discussion on best approach
- [x] run the Flask demo locally as rack-ui package
- [x] put rack-ui demo into RACK file system and start automatically by local docker, opening the new port at startup
- [x] execute sample overlay/nodegroup load
- [x] demonstrate giving Docker access to user-selected ingestion package from host machine
- [x] try new manifest (being developed by Eric)
- [x] initial buttons to load ARCOS / Apache data, using manifest 
- [x] cleanup (error handling, unhardcoding, etc)
- [x] button to reset RACK (with confirmation dialog) _(done and later removed)_
- [x] show load progress 
- [x] add spinner
- [x] remove junk characters from status
- [x] merge to master branch

**Comment by cuddihyge** [comment]
- [ ] another task ?

**Comment by baoluomeng** [comment]
Is this going to be a replacement of RACK Eclipse plugin? What is the motivation behind this? @cuddihyge @kityansiu @pauls4GE

**Comment by pauls4GE** [comment]
As just a no-cli-involved ingestion and basic querying GUI for RACK (I am guessing this will be a part/offshoot of the RiB page that is visible on localhost) aimed at novice users, it makes sense for now. 

Also, our plan is to make such a feature in the RACK Eclipse Plugin as well which will provide two user modes: 1. Advanced Mode and 2. Easy Mode.

**Comment by baoluomeng** [comment]
> 

The RACK plugin is **NOT only** for ontologists. It would be end-to-end tool and is for everyone regardless of their levels of expertise. Most of the features you mentioned were already part of the RACK plugin GUI and also dummy enough for everyone. I am not sure why we want to exclude Eclipse. But right now the only benefit of your approach I can see is that the RACK website and SemTK website would be written in the same language and can easily be integrated together. I am not sure what else the new website GUI would bring to the project. 

Btw, Saswata Paul is planning to take over the RACK plugin and continue the development.

![rack_plugin](https://user-images.githubusercontent.com/49253843/174337221-13fb602b-cc83-49d2-9d4b-5ecb91561004.png)

**Comment by cuddihyge** [comment]
I think the original motivation was a **zero-install option**, and the oxymoronic phrase: ```Eclipse plug-in with 'Easy Mode' ```
Eclipse and plug-ins have historically been fairly complicated for folks to navigate, but the infrastructure is improving. 

If we expect all users to have eclipse and manage a plug-in, then we may not need a separate installation and data-loading UI.

**Comment by cuddihyge** [comment]
spun out issue #747 to track details and features in the rack cli manifest

**Comment by cuddihyge** [comment]
moved some tasks to new issue #750, so this one will close when basic functionality is merged into master and tested.
