### ISSUE TITLE
TA1 LM Overlay and demo better data ingestion.

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#734]
is this possibly confused with #740

**Comment by kityansiu** [comment]
Carter and Mauricio agreed to our proposed change, which is to add Claim-[wasImpactedBy]->REQUIREMENT, and similarly, Claim-[wasImpactedBy]->TEST.  

wasImpactedBy indicates that an entity materially affected another entity and changing the latter might affect or invalidate the former.

Change is additive and should improve the experience for data consumers. We sent Carter and Mauricio sample additions based on the Apache-IngestionPackage-wSW-RACKv10.2-20220531 dataset, which they can replicate/automate in their tool for the next data drop.
