### ISSUE TITLE
Query optimization over multiple graphs

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#737]
Fuseki does not optimize over multiple graphs.
SemTK has the "predicate counts" data which could be used to re-order clauses for optimization.
We're not sure whether SemTK **should** do this, or whether we should leave it to the triplestore.

There are some internal notes on Fuseki from @Ptival [here](https://ge.ent.box.com/file/977325666021?s=353ilxlkl2fo2ga1rujxgt8xmvlngbvu)

**Comment by chrisage** [comment]
covered in related issue (#718)
