### ISSUE TITLE
Automate SemTK jar deployment for Eclipse plug-in dev et. al.

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#745]

**Comment by cuddihyge** [comment]
First idea of deploying via GitHub packages has been abandoned due to:
- SemTK compatibility issues that would be caused by needing to lowercase all the jar names
- Burden of re-configuring all other users' poms with GitHub packages security and new repo URLs

We turned instead to verifying the existing maven deploy process.   Built a jenkins job that runs each weekend and deploys the jars to maven central.   It can easily be kicked off manually for a mid-week higher priority push.

Info on the Semtk wiki https://github.com/ge-semtk/semtk/wiki/Java-API#semtk-java-api is correct and still useful.  Jars are updated much more frequently (and automatically) than before.

**Comment by cuddihyge** [comment]
We could still use a better versioning process for SemTK jars.   Issue new non-SNAPSHOT jars and bump the version number more frequently.

**Comment by baoluomeng** [comment]
We are now deploying SemTK snapshots to OSSRH directory. And I can confirm that we are able to pull the jars from OSSRH directory.
