### ISSUE TITLE
Possible outdated documentation for ingestion packages

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RACK#766]
The format for store_data.csv mentioned in the tutorial for [ingestion packages](https://github.com/ge-high-assurance/RACK/wiki/05-Preparing-Your-Own-Data) does not match the format in the [nodegroups folder](https://github.com/ge-high-assurance/RACK/blob/master/nodegroups/queries/store_data.csv) in the main repository.

**Comment by kityansiu** [comment]
Fixed. Updated with itemType.
