### ISSUE TITLE
Update Wiki to reflect GUI

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#768]
pages to edit
- [x] _welcome.md in the wiki - perhaps put the tools links prominently at the top
- [x] page 04 - still correct.  Add instructions for rack-ui at top.   Move older instruc
- [x] page 02 - open the correct docker port.   Keep the instructions to go to :8080

**Comment by cuddihyge** [comment]
We've made some basic changes for the rack-ui.
@kityansiu may want to do a more comprehensive review.

**Comment by kityansiu** [comment]
I just looked over the updated pages. They look good!
