### ISSUE TITLE
GE Ontology CPS property overloading

### ISSUE THREAD

**Issue by kquick** [ge-high-assurance/RACK#787]
One of the issues revealed by the ASSIST-DV enhancement in https://github.com/ge-high-assurance/RACK/pull/786 is:

```
ERROR: Property http://arcos.turnstile/CPS#implControl was referenced on class http://arcos.turnstile/CPS#Cps, but that property is defined for the unrelated class http://arcos.turnstile/CPS#Connection
ERROR: Property http://arcos.turnstile/CPS#implControl was referenced on class http://arcos.turnstile/CPS#Connection, but that property is defined for the unrelated class http://arcos.turnstile/CPS#Cps
```

This comes from https://github.com/ge-high-assurance/RACK/blob/master/GE-Ontology/ontology/CPS.sadl#L38 and https://github.com/ge-high-assurance/RACK/blob/master/GE-Ontology/ontology/CPS.sadl#L78 which overload a property name.  Recommend changing one of these to avoid overloading.

**Comment by kityansiu** [comment]
fixed with [this](https://github.com/ge-high-assurance/RACK/commit/a0d8992b49f54bd17bd33d9ee9ffbe9a8515ce15) commit
