### ISSUE TITLE
Fix SPARQLgraph CONSTRUCT broken on firefox

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#791]

**Comment by cuddihyge** [comment]
problem seems to be with div.scrollIntoViewIfNeeded() in firefox.

**Comment by cuddihyge** [comment]
Kevin sees this problem when clicking the UI link to SPARQLgraph

**Comment by kquick** [comment]
With the latest dev build, I'm still seeing an error immediately when opening SPARQLgraph from the RackUI:

Error: Error: Script error for: sparqlgraph/js/cookiemanager
http://requirejs.org/docs/errors.html#scripterror
url: http://localhost:8080/iidx-oss/components/requirejs/require.js
line: 166
undefined
column: 17
error: Error: Script error for: sparqlgraph/js/cookiemanager
http://requirejs.org/docs/errors.html#scripterror

**Comment by kquick** [comment]
I see this only with Firefox, but not with Brave or Vivaldi (or Chrome), so perhaps this is just a local Firefox install issue.

**Comment by cuddihyge** [comment]
Paul refuses to take responsibility for the internet
