### ISSUE TITLE
New column-check issues warnings on setup scripts

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#793]
When running the cli/setup-arcos.sh script, ingest_CONTROL and ingest_THREAT steps produce `Input is missing these columns` outputs.  Does it perhaps make sense to suppress these for the setup script so that the user doesn't perceive this as "something is wrong with my installation" (which was my initial knee-jerk response until I remembered the new feature).

**Comment by kityansiu** [comment]
That's a good idea. We can make that change to the setup script.
