### ISSUE TITLE
SemTK ingestion:  URILookup by subtype

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#802]
Prereq for #798 

- [x] rough out a Sparqlgraph UI idea [dan]
- [x] build back end [paul]
- [x] build SPARQLgrpah ui [paul]

**Comment by russell-d-e** [comment]
I think from the UI perspective it can look pretty much the same as any other property:


![Image](https://user-images.githubusercontent.com/62702525/195883595-ab5fe7f8-d259-49b3-902c-cc2a5f0bf0a5.png)

I would maybe use TYPE instead that is shown in the example above subclass and make it bold to distinguish it from the other properties (same as Node) as well as have it directly below the node, but I think that would be enough.

**Comment by cuddihyge** [comment]
![Image](https://user-images.githubusercontent.com/19863188/195942830-4fb95e9d-45a4-4b36-a290-a488d9647edb.png)

I've made it more general.   This is a generic screen dump (I don't have your ontology)
In your case there would be
- ?SAME_AS_TYPE which you would ignore
- ?Primary_type which you would map to a column with the type of the primary instance
- ?Secondary_type which you would map to a column with the  type of the secondary instance

**Comment by cuddihyge** [comment]
I guess it might be better to use _subtype, but technically using the actual type is legal.  IDK.

**Comment by cuddihyge** [comment]
Also noticed that the subtype is used for two purposes:
1. URI lookup
2.  ingestion 

The normal URI Lookup behavior is that subclasses count.   I think that will be the default behavior.

I will try implementing a "!" operator so if you want exactly that subclass, you can put it in the csv cell as "Requirement!" instead of plain "Requirement".  that will cause ONLY exactly Requirement to match a URILookup.

Any thoughts that perhaps this should be the default?  It seems more likely, but a little inconsistent. 

What do you think?   Maybe I need to share an example on Teams instead of this?   @russell-d-e @kityansiu @weisenje   ???

**Comment by cuddihyge** [comment]
I'm checking in my first shot at this functionality.   the docker -dev container
