### ISSUE TITLE
Align GrammaTech SW Component Identifiers

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#820]
**Backgroud** : Boeing's artifact drop (ARCOS_BoeingPhase2_drop3a_software) seems to be missing package specification files. This caused problems when using libadalang to resolve module cross references. We emailed Doug Stuart via MessageCourier on 11/9/2022 with specific examples of package bodies without package specifications. In the meantime, Eric hand edited/corrected SWCOMPONENTs to include in the Apache Ingestion package of 11/21 (Apache-IngestionPackage-wSW-RACKv11-20221121). GT was able to align their data with the hand edits, which is also supplied as part of the 11/21 package.

**Criteria** for resolution: Boeing should supply a complete software package without any missing files. The current "hack" to produce the SWCOMPONENTs for ingestion is not sustainable.

**Comment by cuddihyge** [comment]
Waiting for a response to @kityansiu 's message from Boeing

**Comment by kityansiu** [comment]
Closing this issue because it had to do with Phase 2 data. In Phase 3, Boeing should be exercising the ARCOS tools with a complete software package.
