### ISSUE TITLE
Tunstile data csv has some empty identifiers

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#821]

**Comment by saratge** [comment]
Will get rid of empty identifiers seen in the following CSVs:

https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/TurnstileHighLevelRequirements/HAZARD_HAZARD1.csv

https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/TurnstileHighLevelRequirements/HAZARD_HAZARD2.csv

https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/TurnstileLowLevelRequirements/GE_HighLevelRequirement1.csv

**Comment by saratge** [comment]
https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/TurnstileLowLevelRequirements/GE_HighLevelRequirement2.csv

**Comment by saratge** [comment]
The above CSVs are fixed by commit https://github.com/ge-high-assurance/RACK/commit/47b5b025455d278205a863fb2b6e6ac1bb7104ef
