### ISSUE TITLE
Add copy_graph() capability to CLI & manifest

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#824]
For entity resolution, we'll want to load data "as usual" and then copy everything to the default graph before optimizing.

There is a semtk-python3 function copy_graph() which will need to be accessible through the CLI and manifest.

@glguy is probably the best judge of what type of granularity & flexibility is best.  In other words:  should it be buried inside a "copy-to-default-graph-and-optimize" or should it be available as a separate step in case there are other use-cases for copying graphs during a manifest load.

**Comment by cuddihyge** [comment]
perhaps it would be simpler if manifest just gets  a **single operation** that:

1. copies the loaded data to the default graph  (clearing it first)
2. performs entity resolution (no-op if there's nothing to do)
3. runs the optimization

**Comment by glguy** [comment]
> perhaps it would be simpler if manifest just gets  a **single operation** that:
> 
> 1. copies the loaded data to the default graph  (clearing it first)
> 2. performs entity resolution (no-op if there's nothing to do)
> 3. runs the optimization

Are we assuming there will only be one entity resolution step? I've been expecting we need to support potentially multiple and at different levels. As data sets grow I could see needing to add new ones rather than replace them.
