### ISSUE TITLE
RACK-UI: change user options for loading data / opening SPARQLgraph

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#837]
Any manifest that contains a copy to default graph should trigger the UI somehow to give the user a choice which to load with SPARQLgraph.

- [x] add convenience function to check if manifest contains copy to default graph **(Eric)**
- [x] stop asking user to load data to default graph or not (remove radio buttons) **(Jenny)**
- [x] if manifest has copy step, RACK UI give links to open SPARQLgraph with "as-loaded/original" or "optimized" graphs **(Jenny)** 
- [x] show SPARQLgraph links on load page, rather than on dialog **(Jenny)**
- [x] what if a sub-manifest contains a copy step?  Is this "legal" and if so how should we handle it?

**Comment by glguy** [comment]
Currently you can parse a manifest file and see if one of the steps is to copy to default graph.

I can add a method that specifically checks if the last step in ingestion is to copy to the default graph. Is that what we'd want to check?

**Comment by Ptival** [comment]
Was there some other reason than triggering optimization for allowing the user to disregard the graphs from the manifest and instead load to default graph?

Asked differently, once manifests can express "copy to default graph", do we still need the knob in the UI that lets the user override to default graph? Supposedly, they could do so by modifying their manifest at this point, no?

**Comment by cuddihyge** [comment]
"as-loaded"  and "optimized" are suggestions for the links opening SPARQLgraph

**Comment by cuddihyge** [comment]
@weisenje blocked on @glguy cli python function to tell whether there is a copy to default graph.
