### ISSUE TITLE
Error loading Turnstile data

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#844]
Error when loading Turnstile data via RACK UI:

![Turnstile-error](https://user-images.githubusercontent.com/11859260/204837511-c01e78e8-a9f1-4db9-b96e-4f98fb756d36.png)

**Comment by glguy** [comment]
The ingestion prices for turnstile can probably be updated to not use the ingestion nodegroups. I'd thought that we'd already done this as part of transiting over to the derived ingestion work Paul did

**Comment by cuddihyge** [comment]
DO178c and DO130 manifests are not updated to ingest-by-class.

**Comment by kityansiu** [comment]
i reviewed and tested on my Mac
