### ISSUE TITLE
Missing information for building Rack VM in the README

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#850]
I was having trouble with `packer build rack-box-virtualbox.json`.

After some digging, I found the following steps were added recently in the CI:
```
curl -LOSfs https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20221021.0.0/providers/virtualbox.box
tar -xf virtualbox.box -C RACK/rack-box/focal64
```

But these are never mentioned in `rack-box/README`, as far as I can see.

**Comment by tuxji** [comment]
Thanks for noticing that inadvertent omission.  I'll mention the need to download and unpack an existing ubuntu vagrant box.  However, you can tell GitHub CI to build a RACK virtual machine for you on your own vr/optimize-endpoint branch too.  Just go to RACK's GitHub [page](https://github.com/ge-high-assurance/RACK), click the [Actions](https://github.com/ge-high-assurance/RACK/actions) tab, click on [RACK Build Virtual Machine Workflow](https://github.com/ge-high-assurance/RACK/actions/workflows/manual.yml), click the "Run workflow" button, and fill it in:

![image](https://user-images.githubusercontent.com/5915561/206539665-be6630ed-e828-4907-a2bd-4320882a87d6.png)

Check back one hour later and if all goes well, you will find a build artifact attached to the new workflow (although you may have to re-download the artifact several times before your browser finally downloads a fully complete artifact which unpacks the VM's 2 split zip files successfully).  I blame GitHub's flaky artifact download process for requiring multiple tries to download a large zip.
