### ISSUE TITLE
RACK UI: button to restart Fuseki

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#870]
Add to RACK UI the capability to restart Fuseki.
Likely via a button on a new Utility tab.

**Comment by glguy** [comment]
This feature isn't working for me, and I'm getting inconsistent results when I try to reproduce the failure with manual command invocations. Is anyone else experiencing this failing?

I get messages in my docker console output

```
2023-02-13 16:23:07 fuseki.service: 00:23:06 INFO  Server          :: Apache Jena Fuseki 4.6.1
2023-02-13 16:23:07 fuseki.service: 00:23:07 ERROR Server          :: SPARQLServer: Failed to start server: Failed to bind to 0.0.0.0/0.0.0.0:3030
2023-02-13 16:23:07 fuseki.service: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:3030
```

and when I connect to the docker instance with bash I can see two fuseki processes running (the old one didn't die).

**Comment by glguy** [comment]
I can't reproduce this reliably. Sometimes it works and sometimes it doesn't. We might end up having to hack around it like:

* systemctl stop fuseki
* check that it stopped - kill it until this check succeeds
* systemctl start fuseki

**Comment by Ptival** [comment]
I can confirm that it works for me most of the time, but once I got the same behavior as @glguy , so we should keep an eye on this.

A symptom of the bad behavior is that there end up being two `fuseki` instances: the "old" one, with a very low PID (usually 110), and new ones seem to get spawned at regular interval and die, with increasing PIDs.

**Comment by cuddihy** [comment]
You have the wrong Cuddihy.

**Comment by glguy** [comment]
I've pushed a commit that fixes it in my local docker image. When I originally tested this I copied the script manually into my docker but it seems that I didn't save the correct one back into the repository.

**Comment by glguy** [comment]
It works now. same error in two places. It's rather unreliable to have shell scripts calling each other so the the bug ended up duplicated twice <_<
