### ISSUE TITLE
Cannot enter model or data graph in "Build a Connection" dialog

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#874]
When cache is cleared, can't seem to type in a model graph or a main data graph in the "Build a Connection" dialog box. Looks like the box is meant for selection of existing graphs without the ability to type in something new.

![image](https://user-images.githubusercontent.com/12802455/212123807-7bb237f3-6459-48c6-bf54-9c0d5ec27ee7.png)

**Comment by cuddihyge** [comment]
yeah I guess this is less-than-intuitive design.    If you want to add new graphs, you need to do it on the previous screen.
I don't think we need this for Mar 6 but it should be on the Semtk "List".

**Comment by cuddihyge** [comment]
I've changed it up to allow incomplete connections to be built with some hints you can continue on the next screen.

**Comment by kityansiu** [comment]
Tested. Working!
