### ISSUE TITLE
upgrade RACK box to Ubuntu 22.04

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#885]
Our RACK box is based on Ubuntu 20.04 and uses one Python package (Pillow) with a CVE.  For security, we should transition to Ubuntu 22.04 (update the Python and Pillow versions too) and base the Mar 2023 RACK box on Ubuntu 22.04.  This Pillow package cannot be upgraded to avoid the CVE without also upgrading Ubuntu.

**Comment by tuxji** [comment]
Pull request #917 is ready for review/merge.  Anyone who has authored a Python script in RACK, please take a look to see if this PR will affect your script and whether you're OK with bumping its requirements or not.

**Comment by tuxji** [comment]
PR is merged and team will test dev image.  If testing goes well after 2-3 days, we can close this issue.
