### ISSUE TITLE
Add dataInsertedBy to SAME_AS

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#887]

**Comment by cuddihyge** [comment]
@russell-d-e  says it's already there

**Comment by cuddihyge** [comment]
It's in the nodegroup but not exported by the tool.

**Comment by cuddihyge** [comment]
@russell-d-e @kityansiu can we review this and make sure it is "done"

**Comment by russell-d-e** [comment]
Just check this is done, PROV-S added added a NODE parent class of THING that has the dataInsertedBy relationship and SAME_AS uses this NODE class
