### ISSUE TITLE
SemTK  & fuseki optimize : re-architect

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#888]
SemTK can not optimize fuseki because it doesn't know where it is or whether it has permission.

Some options would be:

1. take this back out of the manifest and make it a RACK-ui function
2. pass un-processed flags from SemTK back to the caller...again RACK-ui sees it and optimizes afterwards
3. pass all needed info to SemTK from RACK (somehow...?)

**Comment by cuddihyge** [comment]
### What SemTK can't do:

- **optimize the default graph** in fuseki

perhaps this could be removed from the manifest

### Non-loading functions of manifest

- what is the **footprint**  (for "view data")
- was **copy-to-default-graph** done (for "view data",   potentially for caller to decide whether to optimize default graph)

**Comment by cuddihyge** [comment]
how do we read "footprint" and "copy-to-default-graph" from the manifest
1. centralized location (SEMTK backend)
2. don't have to send an entire huge zip to ask a small question

**Comment by cuddihyge** [comment]
@glguy it seems we need to take **perform-triplestore--optimization** out of the manifest because the back end is not capable of doing it.  The caller would instead do it either manually or automatically check for **copy-to-default-graph** and do it.

**Comment by glguy** [comment]
I thought we already knew semtk couldn't do it and it was going to ignore that field.

Are you wanting me to move that field to a separate file?
