### ISSUE TITLE
Port CLI default use of http://rack001/model,data

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#891]
@cuddihyge @glguy 

In the CLI we have the following.  These are used in `sparql_connection()` whenever a model or data graph is not otherwise specified.
```
MODEL_GRAPH: Url = Url("http://rack001/model")
DEFAULT_DATA_GRAPH = Url("http://rack001/data")
```
import.yaml files currently do not require model-graph to be specified - if not specified it uses the above.

When porting to SemTK, we can't have "default" model/graph files like above. 

- [x] accept default model/data as a endpoint parameter

**Comment by glguy** [comment]
When I originally wrote that, I did it under the assumption that you needed to mention the connection sources of anything that you were referring to. If you were subtyping models from one connection in another you might want read-only access to the parent class.

That said I suspect what actually happens is that semtk just slams the triples into the triplestore and doesn't care about that. It's probably only relevant to the query side of things. In a future where we had more operations on model import files we might need read access to the derived triples but currently I suspend there's no need for this functionality.
