### ISSUE TITLE
Fix YAML validation for manifest steps array

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#892]
Current SemTK YAML validation does not error if a manifest has an invalid step. 
```
name: 'Animals'
steps:
  - manifestttt: animals.yaml  # this should fail but it doesn't
```
I've added a test that is currently failing: UtilityTest.testValidateYaml() in [this file](https://github.build.ge.com/semtk/semtk-opensource/blob/load-ingestion-package/sparqlGraphLibrary/src/test/java/com/ge/research/semtk/utility/test/UtilityTest.java)

**Comment by glguy** [comment]
@weisenje I'll take a look

**Comment by glguy** [comment]
@weisenje I can't follow the link you've mentioned in the top of the issue. Seems to be GE internal only. Is this code on github somewhere?

**Comment by glguy** [comment]
I’m aligned with using the older spec solution. We’re not (deliberately) relying on the behaviors in the new spec, so there’s no particular need to use the latest.
