### ISSUE TITLE
Implement IngestCsvConfig

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#895]
Port INGEST_CSV_CONFIG from Python
- [x] make all 3 config file types extend a subclass
- [x] validate YAML against schema
- [x] model-graphs
- [x] data-graph
- [x] extra-data-graphs  (used in Ap1206.zip)
- [x] step: csv by class
- [x] step: csv by nodegroup (used in Ap1206.zip)

Not used in IngestionPackage.zip OR Ap-1206.zip.  Team confirmed do NOT need to port:
- [x] step: owl - **this is used in Turnstile-IngestionPackage - porting it**
- step: nodegroup_json
- step: count nodegroup

**Comment by glguy** [comment]
OWL is the lowest priority. I don't know if any of the other teams are still using their own custom nodegroups or not.

**Comment by glguy** [comment]
@weisenje Yup, looks like I was wrong. I added that thinking it would be useful for data specified from SADL but I didn't know it ever actually got used.
