### ISSUE TITLE
Test on RACK Turnstile example

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#907]
**Minimum**: try loading the Turnstile ingestion package using the SemTK manifest loader
**Better**: zip up the [Turnstile ingestion package](https://github.com/ge-high-assurance/RACK/tree/master/Turnstile-Example/Turnstile-IngestionPackage) and add it to the suite of SemTK JUnit tests

**Comment by kityansiu** [comment]
No objection. But you might have to double check the ingestion package. Simply zipping it up may not work. For example, line 11 in manifest.yaml assumes turnstile.yaml will be part of the zip.

**Comment by kityansiu** [comment]
Yes, please go ahead and manually create a self-containing zip. At one point, I wanted to update this Turnstile ingestion package so that it's a use case for both the RACK IDE and for the RACK UI page, but never got around to it. Please feel free to update the files on the repo. For example, the Load-TurnstileData.sh script is out of date with our current philosophy of loading via manifest.

**Comment by glguy** [comment]
I'll take a look. The manifest build command should handle all the filepath issues.

**Comment by glguy** [comment]
@weisenje I was able to load the zip file generated from the command: `rack manifest build manifest.yaml turnstile` which produces a `turnstile.zip` in the current directory.

**Comment by kityansiu** [comment]
I love the idea of using `rack manifest build`! But the problem I ran into was Windows couldn't find files specified with a backward slash. After I manually changed the contents of the .yaml files, for example, in manifest.yaml:

from
```
steps:
- manifest: 00_manifest\turnstile.yaml
- data: 06_data\import.yaml
...
```
to 
```
steps:
- manifest: 00_manifest/turnstile.yaml
- data: 06_data/import.yaml
...
```
then everything worked. Did anyone else experience this?

**Comment by glguy** [comment]
I haven't tried on Windows yet. I was hoping that by using the Python tooling for generating file paths that it would generate paths that it understood! Given that that doesn't seem to be the case I'll investigate now.
