### ISSUE TITLE
copy-to-default-graph : can we fix it before we really start using it

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#912]
Copy-to-default-graph is also very Fuseki specific and always tied to optimization, which we are not doing during manifest loader.

Before there are any official manifests released that use this feature, could we change it to:

**copy-results-to-graph:   uri://DefaultGraph**    (  or "urn:x-arq:DefaultGraph" )
**perform-entity-resolution:  uri://DefaultGraph**

then the default graph could be in the footprint.

Callers could check the footprint for the default graph and fuseki and decide whether to optimize.

If/when we move to another triplestore that uses datasets differently, we could still copy all the results to a different graph for entity resolution, or other purposes.

- [x] change `copy-to-default-graph: true` to `copy-to-graph: uri://DefaultGraph`
- [x] change `perform-entity-resolution: true` to `perform-entity-resolution:  uri://DefaultGraph`
- [x] REMOVE `load(...boolean loadToDefaultGraph...)`  (in Python: `boolean default_graph`)
- [x] corresponding Python changes
(No released ingestion packages are using the above yet.)

**Comment by cuddihyge** [comment]
@weisenje @glguy  comments?

There is a non-zero chance we'll actually need this functionality since Fuseki is getting slow and other solutions handle the default graph a little differently.

**Comment by glguy** [comment]
I'm OK with this, but it does make ingestion packages triplestore-specific where before that tooling could be held responsible to know which default graph URI to use based on the runtime flag indicating which triplestore was being used.

**Comment by cuddihyge** [comment]
**loadToDefaultGraph** could be changed to **loadtoGraph** and be a graph name instead of boolean.   Caller could specify uri://DefaultGraph ( or "urn:x-arq:DefaultGraph" ) if desired.

**Comment by glguy** [comment]
If we're going to make it easy to bake fuseki conventions into the manifest file, then we should also add the triple-store-type field to the manifest file. Ingestion packages will become more specific to the triple store being loaded, so we'll need a way to capture that.

**Comment by cuddihyge** [comment]
Do you mean **uri://DefaultGraph ( or "urn:x-arq:DefaultGraph" )** ?
Those are not fuseki conventions.  They are a w3c standard.   Fuseki interprets them differently.
I don't understand where you're going.

**Comment by glguy** [comment]
You mentioned that we'd only want to copy to this particular graph on Fuseki and that other triple stores might want a different target.
