### ISSUE TITLE
Add http://rack001/data to Turnstile ingestion package

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#923]
Turnstile loads model/data to 4 graphs - but only 3 are captured in the footprint.  Need to add `http://rack001/data`?

![Image](https://user-images.githubusercontent.com/11859260/221579205-3b25d078-3520-4ffc-9755-bf65ad8737ce.png)

**Comment by glguy** [comment]
I don't see which data was being loaded into the data graph. I see that that URI is mentioned in some nodegroups, but those wouldn't affect the footprint.
