### ISSUE TITLE
Slow Startup RiB Container on Apple M1

### ISSUE THREAD

**Issue by chrisage** [ge-high-assurance/RACK#928]
The rack-box docker image is only built for linux/amd64 OS/ARCH resulting in slow startup times on Apple Silicone (tested on M1) - requesting RiB docker image distribution for linux/arm64

**Comment by glguy** [comment]
RACK without a native build on M1 macOS is basically unusable for the production ingestion package. I've been using a locally packed docker image against the `arm64v8/ubuntu:22.04` base image and it's working great. I don't know how to automate the construction of that using Github actions, myself, however.

**Comment by chrisage** [comment]
aarm64 images must be built using the same OS/arch. Options include using 
1. github arch provision action (qemu with docker buildx) - https://github.com/marketplace/actions/run-on-architecture

**Comment by chrisage** [comment]
To Build M1 RACK Image locally (on an M1 machine):
1. Update the `RACK/rack-box/rack-box-docker.json` builder to `"platform": "linux/arm64/v8",` and `pull: true`
2. Download the installation package (files) from the latest successful GitHub action
3. Expanded the downloaded files directory and copy to RACK/rack-box/files
4. Rebuild & Replace the rack-cli.tar.gz file (needed for arch specific python deps):
	a. cd /RACK/cli
	b. change the PyYaml rep in requirements.txt to v6.0.1
	c. install reqs with `pip3 wheel --wheel-dir=wheels -r requirements.txt`
	d. delete all installed wheels from ./wheels except for the semtk-python library
	d. zip entire cli library into RACK/rack-box/files place: `tar -zcvf rack-cli.tar.gz ./RACK/`
	e. modify the `RACK/rack-box/install.sh` script to build the RACK CLI with:
		# under cd "/home/${USER}/RACK/cli/"
		pip3 wheel --wheel-dir=wheels -r requirements.txt
		pip3 wheel --wheel-dir=wheels .
5. Re-run packer build rack-box-docker.json from RACK/rack-box

**Comment by chrisage** [comment]
See Github Runners (and tool info) @ 
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
And self-hosted M1 runners here:
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

**Comment by tuxji** [comment]
I understand we cannot automate the CI build of an arch64 RACK image except on an arch64 github action runner, which would have to be a standalone (self-hosted) machine available somewhere on the Internet.  Still, you can build the arch64 RACK image manually on a Mac M1 computer using the installation package (files) from the latest successful GitHub action.  If you can push the built image to Docker Hub as well (it should be just a matter of granting your account the necessary privilege), then RACK users will be able to download and run the appropriate image for their architecture.

**Comment by chrisage** [comment]
Putting this ticker on the nice-to-haves due to cost of running standalone.

**Comment by glguy** [comment]
I haven't automated the process, but when we make the next release I can build a docker image to update for it
