### ISSUE TITLE
Ingestion package loader use logging ERROR WARNING INFO

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#931]
- [x] prepend progress log lines with ERROR WARNING INFO tags _(pushed to RACK)_
- [x] provide Java methods to parse log level and message from a given log line  _(pushed to RACK)_
- [x] made a [separate issue](https://github.com/ge-high-assurance/RACK/issues/936) to consider any client changes

**Comment by cuddihyge** [comment]
note:  remember to check ERROR.  If there are multiple lines, the others might better be labelled DEBUG:  or INFO:  whatever

**Comment by glguy** [comment]
I think this makes sense. For some reason we're instantiating our own logger instance at the top of the cli. I'm going to check with @Ptival to remember why. I'm just curious to see what mind happen if the semtk python3 bindings were to use the system logger and not this one.

**Comment by chrisage** [comment]
> @glguy, @chrisage: sample output below. Please give a thumbs-up if this format is fine.
> 
> ```
> INFO: Loading manifest for 'Entity Resolution'...
> INFO: Clear graph http://junit/G7JZH4J3E/200005868/auto/rack001/model
> INFO: Loading manifest for 'RACK ontology'...
> INFO: Load OWL OwlModels\AGENTS.owl to http://junit/G7JZH4J3E/200005868/auto/rack001/model
> INFO: Store nodegroups
> INFO: Stored: JUNIT query Files of a Given Format
> INFO: Stored: JUNIT query Requirements without Tests
> INFO: Load CSV Package-1\PROV_S_ACTIVITY1.csv as class http://arcos.rack/PROV-S#ACTIVITY
> WARNING: Input is missing these columns: endedattime, goal_identifier
> INFO: Clear graph uri://DefaultGraph
> INFO: Copy graph http://junit/G7JZH4J3E/200005868/auto/rack001/model to uri://DefaultGraph
> INFO: Successfully copied http://junit/G7JZH4J3E/200005868/auto/rack001/model into urn:x-arq:DefaultGraph
> INFO: Perform entity resolution in uri://DefaultGraph
> INFO: Load complete
> ```
> 
> Or for an error condition:
> 
> ```
> ERROR: Cannot find a top-level manifest in resource14457517151095630833.zip
> ```

LGMT! Solves the problem of merging multiple output streams (ERR/INFO/WARNING) into one by prefixing the classification. As discussed, these statements are streamed real-time and can be amended by the client (e.g. with timestamps).

**Comment by glguy** [comment]
The downside here is that the client can't do client-specific things to make this rendering pretty. With the tags on lines I can do console color coding and in the RACK-UI you can do HTML coloring of output lines.

**Comment by glguy** [comment]
@weisenje Minor issue, but the space seems to be missing after `DEBUG:` to match the other messages.
