### ISSUE TITLE
RACK UI warning banner

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#933]
Enable RACK UI to optionally display a configurable warning banner on the load page, 

Will use this to warn not to upload sensitive data on a given installation.

**Comment by cuddihyge** [comment]
I mucked with the directory permissions, particularly on the RACK stage01 server.
I changed the file name to config.sample.yml and added config.yml to .gitignore.
Now we can fetch and restart without wrecking config.yml, and sample version is there for reference.
