### ISSUE TITLE
How do you install rack-ui incl turnstile owl without docker

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#934]

**Comment by tuxji** [comment]
Take a look at how the [RACK Continuous Integration Workflow](https://github.com/ge-high-assurance/RACK/blob/master/.github/workflows/continuous.yml) runs RACK tests on the CI runner box without using Docker:

```yml
    - name: Install rack-box on runner
      run: |
        mkdir -p /tmp/files
        for f in RACK/rack-box/files/*; do
          ln -s $(realpath $f) /tmp/files/$(basename $f)
        done
        python3 -m pip install --upgrade pip setuptools wheel
        sudo bash RACK/rack-box/scripts/install.sh $USER
```

You need to download a set of rack-box-files from the build artifacts attached to the most recent [workflow run](https://github.com/ge-high-assurance/RACK/actions/runs/4431253494) and unpack them in your RACK/rack-box/files directory first, but once you have these files in hand, you can install the RACK box files locally on your machine without any use of Docker.

**Comment by chrisage** [comment]
question answered by @tuxji - no action needed
