### ISSUE TITLE
Optimize.sh (and restart-fuseki.sh) not working reliably

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#945]
To reproduce:
Start a new Docker container (I used dev), and run the optimize.sh (in /home/ubuntu/RACK/cli) script a few times - some will fail.

**Comment by glguy** [comment]
@weisenje The extra kill -9 was an attempt to knock out the process in the case that systemctl failed to finish the job. When things are working correctly the process will already by gone by the time we get to the kill command. In general, I do not yet understand why restarting fuseki fails.

**Comment by glguy** [comment]
OH, I see now. I missed that commit earlier. Yeah, your fix should go in.

**Comment by glguy** [comment]
the restart script is updated now
