### ISSUE TITLE
Add Turnstile zip as a GitHub release asset

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#946]
Make a Turnstile ingestion package available as a GitHub release asset

- [x] create Turnstile ingestion package, add manually to V12 release
- [x] automate for future releases

**Comment by kquick** [comment]
The portion that would generate the Turnstile Build and the associated data is here: https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/Load-TurnstileData.sh#L100-L109

The only change needed would be to add `-o {OWLFILE}` to the `ingest_data` command at the end.

I don't think we want to change the `Load-TurnstileData.sh` file itself, but I'm not sure where this work is being done, so I can identify this as what is needed for wherever we are scripting this artifact-generation process.

**Comment by tuxji** [comment]
> I don't think we want to change the Load-TurnstileData.sh file itself, but I'm not sure where this work is being done, so I can identify this as what is needed for wherever we are scripting this artifact-generation process.

We script the artifact-generation process in this [.github/workflows/release.yml](https://github.com/ge-high-assurance/RACK/blob/master/.github/workflows/release.yml) file.  I don't suppose we want the Turnstile model, nodegroups, and data to be loaded into the RACK box, so we would NOT modify the `.github/workflows/assemble-files.yml`, `.github/workflows/build-docker-image.yml`, `.github/workflows/build-virtual-machine.yml`, or `rack-box/scripts/install.sh` files.  Instead, I suppose we want to append a new job to the bottom of `.github/workflows/release.yml` which will start up the newly built rack-box docker image, run `cli/setup-turnstile.sh` to populate the rack-box with the Turnstile model and nodegroups, run `Turnstile-Example/Turnstile-IngestionPackage/Load-TurnstileData.sh` to populate the rack-box with the Turnstile data, run whatever additional step is needed to generate the ingestion package, kill the rack-box container since we no longer need it, and upload the ingestion package as a GitHub release artifact.  Does that sound correct?

**Comment by tuxji** [comment]
OK, let's rename the `Load-TurnstileData.sh` script to a better name like `Assemble-TurnstileData.sh` (pick your choice of assemble, generate, etc.).  Then the new CI job only needs to clone the RACK repository, call that script to create `turnstile-verXYZ.zip`, and attach the ingestion package to the release page.  Right?

**Comment by kquick** [comment]
I think that's generally right.  Here's more details as I see them, but I'd want others to confirm this:

1. We might also need to call https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/runall.sh to ensure all the CDR files are up to date.  
2. We would remove all the `Load_TurnstileData.sh` portions that use the rack-cli to load data, ensuring that those are already covered by the manifest file (https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/manifest.yaml) and verify that the manifest file is complete. 
3. The portion of `Load_TurnstileData.sh` that performs the build and `ingest_data` would just need to use the `-o` flag previously mentioned to generate an OWL file output
4. We rename `Load_TurnstileData.sh` as described by @tuxji (and perhaps move it up to the parent directory?).
5. The manifest file should be updated to also load that OWL file
6. The CI job would tar up the OWL file, all the output from step 1, the manifest.yaml, and anything else referenced by the latter, then upload that as a build artifact.
7.  We also need to update https://github.com/ge-high-assurance/RACK/blob/master/Turnstile-Example/Turnstile-IngestionPackage/README.md to describe using the manifest approach (run step 1, step 3, then the `rack manifest import ...` that Eric described above on either the local manifest file or the generated tarfile artifact.

Does the above sound correct, @glguy and @kityansiu ?

**Comment by cuddihyge** [comment]
@kquick will do 2,3,4 and kick it over to Eric.

**Comment by glguy** [comment]
The `Assemble-TurnstileData.sh` now generates `turnstile-ingestion-package.zip`

**Comment by tuxji** [comment]
Changes are done.  A test CI job (https://github.com/ge-high-assurance/RACK/actions/runs/4640545719) has successfully built turnstile-ingestion-package.zip and uploaded it to artifacts.  I've downloaded the ingestion package and verified it contains the same contents as the ingestion package I built in my checkout.  The release workflow will also call the same assemble-turnstile-data.yml to upload the ingestion package to the release. 

The test CI job didn't build the virtual machine successfully, but that's a reoccurring problem with the macos-12 runner we don't need to worry about right now.

**Comment by tuxji** [comment]
> The downloaded file name is `turnstile-ingestion-package.zip.zip` (double zip extension). Is this something that should be corrected?

No, the downloaded file is really double-zipped (unzip the .zip.zip and you get a .zip which you need to unzip again).  We can't correct the double-zipping, but the double-zipping happens only when uploading the .zip to the run's build artifacts.  The double-zipping won't happen when uploading the .zip to the release page, so we'll be fine there.
