### ISSUE TITLE
fix Rack-ui "load" bug showing up on leb1rackstage01

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#974]
There appears to be a subtle problem with the disccache use of {get_tempdir()}.   When we tried loading an ingestion package, no error appeared but it did nothing.  The log said "sqlite3.OperationalError: no such table: Cache".    The problem was fixed with a restart.   Stackoverflow browsing leads me to believe there is a problem with the file being used to store the diskcache.   So the tmp file was probably deleted.    We might need a better strategy.   Problem might be reproducable by using a hard-coded cache file and deleting it while the program is running.
- [ ] fix error message:  load fails with no error message except to the log:  sqlite3.OperationalError: no such table: Cache
- [ ] fix the problem

Might be a fluky low priority if we never see it again.  Might be worth a look.

**Comment by chrisage** [comment]
Cannot reproduce
