### ISSUE TITLE
SemTK/SPARQLgraph restriction explorer

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#976]
SPARQLgraph "explore restrictions" screen to improve ability to address quantified cardinality from model ("has at most...")
- show violations vs incomplete (> max cardinality vs < min)
- show frequency as percentage of target class
- browse the violating URI (like a construct query)

**Comment by cuddihyge** [comment]
![Image](https://github.com/ge-high-assurance/RACK/assets/19863188/7e75ccdb-5e3b-4b24-b45a-5cf06967bc73)

**Comment by kityansiu** [comment]
completed.
